import express from 'express';
import { readFileSync } from 'node:fs';
import { importPKCS8, SignJWT } from 'jose';
import { Db } from './db.js';
import { DomainError } from '../shared/types.js';
import { safeEqual } from './security.js';

const db=new Db();const app=express();app.use(express.json({limit:'256kb'}));
app.use((req,_res,next)=>{const configured=process.env.PROJECTBOARD_BROKER_SHARED_SECRET??'';if(configured.length<24||!safeEqual(configured,String(req.headers['x-broker-secret']??'')))return next(new DomainError(401,'BROKER_AUTH_FAILED','Broker authentication failed'));next()});

async function githubInstallationToken(installationId:string,repositoryId:string,permission:'read'|'write'):Promise<{token:string;expiresAt:string;providerTokenId?:string}>{
  const appId=process.env.GITHUB_APP_ID,keyFile=process.env.GITHUB_APP_PRIVATE_KEY_FILE;if(!appId||!keyFile)throw new DomainError(503,'GITHUB_APP_NOT_CONFIGURED','GitHub App is not configured');
  const key=await importPKCS8(readFileSync(keyFile,'utf8'),'RS256');const now=Math.floor(Date.now()/1000);const jwt=await new SignJWT({}).setProtectedHeader({alg:'RS256'}).setIssuer(appId).setIssuedAt(now-30).setExpirationTime(now+540).sign(key);
  const response=await fetch(`https://api.github.com/app/installations/${installationId}/access_tokens`,{method:'POST',headers:{authorization:`Bearer ${jwt}`,accept:'application/vnd.github+json','user-agent':'ProjectBoard-Broker','x-github-api-version':'2022-11-28'},body:JSON.stringify({repository_ids:[Number(repositoryId)],permissions:{contents:permission}})});
  const data=await response.json() as any;if(!response.ok)throw new DomainError(502,'PROVIDER_TOKEN_FAILED',data.message??'Provider token request failed');return{token:data.token as string,expiresAt:data.expires_at as string};
}
const activeTokens=new Map<string,{provider:string;token:string;providerTokenId?:string;repositoryId:string}>();
async function gitlabToken(_installation:any,repositoryId:string,permission:'read'|'write'){
  const tokenFile=process.env.GITLAB_BROKER_TOKEN_FILE;if(!tokenFile)throw new DomainError(503,'GITLAB_BROKER_CONFIGURATION_REQUIRED','GitLab Broker token file is not configured');
  const brokerToken=readFileSync(tokenFile,'utf8').trim();const expires=new Date(Date.now()+86400_000).toISOString().slice(0,10);
  const response=await fetch(`${process.env.GITLAB_BASE_URL??'https://gitlab.com'}/api/v4/projects/${encodeURIComponent(repositoryId)}/access_tokens`,{method:'POST',headers:{'private-token':brokerToken,'content-type':'application/json'},body:JSON.stringify({name:`projectboard-${permission}-${Date.now()}`,scopes:[permission==='read'?'read_repository':'write_repository'],access_level:30,expires_at:expires})});
  const data=await response.json() as any;if(!response.ok)throw new DomainError(502,'PROVIDER_TOKEN_FAILED',data.message??'GitLab project token request failed');return{token:data.token as string,expiresAt:new Date(Date.now()+3600_000).toISOString(),providerTokenId:String(data.id)};
}
async function issue(binding:any,permission:'read'|'write'){const install=db.get<any>('SELECT * FROM git_installations WHERE id=?',binding.installation_id);if(!install)throw new DomainError(409,'INSTALLATION_MISSING','Provider installation missing');return install.provider==='github'?githubInstallationToken(install.external_installation_id,binding.external_repository_id,permission):gitlabToken(install,binding.external_repository_id,permission)}
async function revokeActive(id:string){const active=activeTokens.get(id);if(!active)return;if(active.provider==='github')await fetch('https://api.github.com/installation/token',{method:'DELETE',headers:{authorization:`token ${active.token}`,accept:'application/vnd.github+json','user-agent':'ProjectBoard-Broker'}});if(active.provider==='gitlab'&&active.providerTokenId){const broker=readFileSync(process.env.GITLAB_BROKER_TOKEN_FILE!,'utf8').trim();await fetch(`${process.env.GITLAB_BASE_URL??'https://gitlab.com'}/api/v4/projects/${encodeURIComponent(active.repositoryId)}/access_tokens/${active.providerTokenId}`,{method:'DELETE',headers:{'private-token':broker}})}activeTokens.delete(id)}

app.post('/internal/observer-credential',async(req,res,next)=>{try{const binding=db.get<any>('SELECT * FROM repository_bindings WHERE external_repository_id=?',req.body.repositoryId);if(!binding)throw new DomainError(404,'REPOSITORY_NOT_BOUND','Repository not bound');const issuance=db.id();try{const result=await issue(binding,'read');activeTokens.set(issuance,{provider:binding.provider,token:result.token,providerTokenId:result.providerTokenId,repositoryId:binding.external_repository_id});db.run('INSERT INTO git_credential_issuances VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',issuance,binding.provider,binding.installation_id,binding.external_repository_id,null,null,null,'observer',JSON.stringify({contents:'read'}),db.now(),result.expiresAt,null,'issued',null);res.json({...result,providerTokenId:undefined,repositoryId:binding.external_repository_id,permission:'read',issuanceId:issuance})}catch(e:any){db.run('INSERT INTO git_credential_issuances VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',issuance,binding.provider,binding.installation_id,binding.external_repository_id,null,null,null,'observer',JSON.stringify({contents:'read'}),null,null,null,'failed',e.code??'PROVIDER_FAILED');throw e}}catch(e){next(e)}});
app.post('/internal/runner-credential',async(req,res,next)=>{try{const lease=db.get<any>(`SELECT l.*,w.project_id,w.assignee_kind,w.assignee_id,b.* FROM leases l JOIN runner_runs rr ON rr.lease_id=l.id AND rr.id=? AND rr.agent_id=l.agent_id AND rr.ended_at IS NULL JOIN work_items w ON w.id=l.work_item_id JOIN repository_bindings b ON b.project_id=w.project_id WHERE l.id=? AND l.agent_id=?`,req.body.runId,req.body.leaseId,req.body.agentId);if(!lease||lease.released_at||lease.expires_at<=db.now())throw new DomainError(409,'LEASE_INVALID','Active lease required');if(lease.assignee_kind!=='agent'||lease.assignee_id!==req.body.agentId)throw new DomainError(403,'ASSIGNMENT_MISMATCH','Agent is not current executor');if(!db.get('SELECT 1 FROM agent_project_grants WHERE agent_id=? AND project_id=?',req.body.agentId,lease.project_id))throw new DomainError(403,'PROJECT_GRANT_REQUIRED','Agent is not enabled');const issuance=db.id();try{const result=await issue(lease,'write');const expiresAt=new Date(Math.min(new Date(result.expiresAt).getTime(),new Date(lease.expires_at).getTime(),Date.now()+3600_000)).toISOString();activeTokens.set(issuance,{provider:lease.provider,token:result.token,providerTokenId:result.providerTokenId,repositoryId:lease.external_repository_id});db.run('INSERT INTO git_credential_issuances VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',issuance,lease.provider,lease.installation_id,lease.external_repository_id,req.body.agentId,req.body.runId,lease.id,'runner',JSON.stringify({contents:'write'}),db.now(),expiresAt,null,'issued',null);res.json({token:result.token,expiresAt,repositoryId:lease.external_repository_id,cloneUrl:lease.clone_url,permission:'write',issuanceId:issuance})}catch(e:any){db.run('INSERT INTO git_credential_issuances VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',issuance,lease.provider,lease.installation_id,lease.external_repository_id,req.body.agentId,req.body.runId,lease.id,'runner',JSON.stringify({contents:'write'}),null,null,null,'failed',e.code??'PROVIDER_FAILED');throw e}}catch(e){next(e)}});
app.post('/internal/revoke',async(req,res,next)=>{try{const now=db.now();const rows=db.all<any>('SELECT id FROM git_credential_issuances WHERE run_id=? AND agent_id=? AND revoked_at IS NULL',req.body.runId,req.body.agentId);for(const row of rows)await revokeActive(row.id);db.run('UPDATE git_credential_issuances SET revoked_at=? WHERE run_id=? AND agent_id=? AND revoked_at IS NULL',now,req.body.runId,req.body.agentId);res.json({revoked:true,at:now})}catch(e){next(e)}});
app.post('/internal/revoke-issuance',async(req,res,next)=>{try{await revokeActive(req.body.issuanceId);db.run('UPDATE git_credential_issuances SET revoked_at=? WHERE id=? AND revoked_at IS NULL',db.now(),req.body.issuanceId);res.json({revoked:true})}catch(e){next(e)}});
app.use((err:any,_req:any,res:any,_next:any)=>res.status(err.status??500).json({error:{code:err.code??'BROKER_ERROR',message:err.status?err.message:'Broker internal error'}}));
const port=Number(process.env.PROJECTBOARD_BROKER_PORT??3334);app.listen(port,'127.0.0.1',()=>console.log(`Git Credential Broker listening on 127.0.0.1:${port}`));
setInterval(async()=>{const rows=db.all<any>(`SELECT i.id FROM git_credential_issuances i LEFT JOIN leases l ON l.id=i.lease_id WHERE i.revoked_at IS NULL AND i.result='issued' AND (i.expires_at<=? OR (i.lease_id IS NOT NULL AND (l.released_at IS NOT NULL OR l.expires_at<=?)))`,db.now(),db.now());for(const row of rows){await revokeActive(row.id).catch(()=>undefined);db.run('UPDATE git_credential_issuances SET revoked_at=? WHERE id=?',db.now(),row.id)}},60_000).unref();
