import { createHmac, randomUUID } from 'node:crypto';
import type { Db } from './db.js';
import type { Actor } from '../shared/types.js';
import { DomainError } from '../shared/types.js';
import { safeEqual } from './security.js';
import { audit, timeline } from './audit.js';

export class GitIntegration {
  constructor(private db:Db){}
  verifyWebhook(provider:string,body:Buffer,headers:Record<string,any>){if(provider==='github'){const secret=process.env.GITHUB_WEBHOOK_SECRET;if(!secret)throw new DomainError(503,'GIT_NOT_CONFIGURED','GitHub webhook secret not configured');const expected='sha256='+createHmac('sha256',secret).update(body).digest('hex');if(!safeEqual(expected,String(headers['x-hub-signature-256']??'')))throw new DomainError(401,'INVALID_SIGNATURE','Invalid webhook signature');return String(headers['x-github-delivery']??'')}const secret=process.env.GITLAB_WEBHOOK_SECRET;if(!secret||!safeEqual(secret,String(headers['x-gitlab-token']??'')))throw new DomainError(401,'INVALID_SIGNATURE','Invalid webhook signature');return String(headers['x-gitlab-event-uuid']??headers['x-request-id']??'')}
  webhook(provider:string,body:Buffer,headers:Record<string,any>){const delivery=this.verifyWebhook(provider,body,headers);if(!delivery)throw new DomainError(422,'DELIVERY_ID_REQUIRED','Delivery id required');if(this.db.get('SELECT 1 FROM webhook_deliveries WHERE provider=? AND delivery_id=?',provider,delivery))return{duplicate:true};const data=JSON.parse(body.toString('utf8'));this.db.transaction(()=>{this.db.run('INSERT INTO webhook_deliveries VALUES(?,?,?,?)',provider,delivery,this.db.now(),'accepted');audit(this.db,{type:'system',id:null},'git.webhook','webhook_delivery',delivery,null,{provider,event:headers['x-github-event']??headers['x-gitlab-event']},'webhook')});return{accepted:true,delivery,needsObserverFetch:true,payloadRepositoryId:String(data.repository?.id??data.project?.id??'')}}
  async reconcilePush(provider:string,data:any){const repositoryId=String(data.repository?.id??data.project?.id??'');const branch=String(data.ref??'').replace('refs/heads/','');if(!repositoryId||!branch)return{scanned:0,linked:0};const binding=this.db.get<any>('SELECT * FROM repository_bindings WHERE provider=? AND external_repository_id=?',provider,repositoryId);if(!binding)return{scanned:0,linked:0};const broker=process.env.PROJECTBOARD_BROKER_URL??'http://127.0.0.1:3334';const headers={'content-type':'application/json','x-broker-secret':process.env.PROJECTBOARD_BROKER_SHARED_SECRET??''};const issued=await fetch(`${broker}/internal/observer-credential`,{method:'POST',headers,body:JSON.stringify({repositoryId})});const credential=await issued.json() as any;if(!issued.ok)throw new DomainError(502,'OBSERVER_CREDENTIAL_FAILED',credential.error?.message??'Observer credential failed');try{let commits:any[]=[];if(provider==='github'){const fullName=data.repository?.full_name;const response=await fetch(`https://api.github.com/repos/${fullName}/commits?sha=${encodeURIComponent(branch)}&per_page=100`,{headers:{authorization:`Bearer ${credential.token}`,accept:'application/vnd.github+json','user-agent':'ProjectBoard'}});if(!response.ok)throw new DomainError(502,'PROVIDER_FETCH_FAILED','Could not reconcile GitHub push');commits=await response.json() as any[]}else{const response=await fetch(`${process.env.GITLAB_BASE_URL??'https://gitlab.com'}/api/v4/projects/${encodeURIComponent(repositoryId)}/repository/commits?ref_name=${encodeURIComponent(branch)}&per_page=100`,{headers:{authorization:`Bearer ${credential.token}`}});if(!response.ok)throw new DomainError(502,'PROVIDER_FETCH_FAILED','Could not reconcile GitLab push');commits=await response.json() as any[]}let linked=0;const candidates=this.db.all<any>('SELECT id FROM work_items WHERE project_id=?',binding.project_id);for(const commit of commits){const message=String(commit.commit?.message??commit.message??commit.title??'');for(const item of candidates){const boundary=new RegExp(`(^|[^A-Z0-9-])${item.id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^A-Z0-9-]|$)`,'i');if(!boundary.test(message))continue;try{this.recordCommit({type:'system',id:null},item.id,{repositoryId,sha:commit.sha??commit.id,message,author:commit.commit?.author?.name??commit.author_name,branch,files:[]});linked++}catch(error){if(!(error instanceof DomainError&&error.code==='GIT_OWNERSHIP_REJECTED'))throw error}}}return{scanned:commits.length,linked}}finally{await fetch(`${broker}/internal/revoke-issuance`,{method:'POST',headers,body:JSON.stringify({issuanceId:credential.issuanceId})})}}
  recordCommit(actor:Actor,workItemId:string,input:any){const item=this.db.get<any>('SELECT w.*,r.external_repository_id,r.id repository_binding_id FROM work_items w JOIN repository_bindings r ON r.project_id=w.project_id WHERE w.id=?',workItemId);if(!item)throw new DomainError(404,'NOT_FOUND','Work item or repository binding not found');const expectedBranch=`projectboard/${this.db.get<any>('SELECT project_key FROM projects WHERE id=?',item.project_id)?.project_key}/${item.number}`;if(input.repositoryId!==item.external_repository_id||input.branch!==expectedBranch)throw new DomainError(422,'GIT_OWNERSHIP_REJECTED','Repository or branch rejected');const boundary=new RegExp(`(^|[^A-Z0-9-])${item.id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^A-Z0-9-]|$)`,'i');if(!boundary.test(input.message))throw new DomainError(422,'WORK_ITEM_ID_MISSING','Commit message lacks full work item ID');try{const id=randomUUID();this.db.run('INSERT INTO git_commit_evidence VALUES(?,?,?,?,?,?,?,?,?)',id,workItemId,input.repositoryId,input.sha,input.message,input.author??null,input.branch,JSON.stringify(input.files??[]),this.db.now());timeline(this.db,workItemId,'git_commit',item.stage,actor,{sha:input.sha,message:input.message,author:input.author,branch:input.branch,files:input.files});audit(this.db,actor,'git.commit_linked','commit',input.sha,item.project_id,{repositoryId:input.repositoryId,branch:input.branch},'runner');return{id,duplicate:false}}catch(e:any){if(String(e.message).includes('UNIQUE'))return{duplicate:true};throw e}}
}
