import express, { type Application, type Request, type Response, type NextFunction } from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { Db } from './db.js';
import { DomainError } from '../shared/types.js';
import { authMiddleware, csrfMiddleware, login } from './auth.js';
import { hashOpaque, hashPassword, randomToken, renderMarkdown, validatePassword } from './security.js';
import { requireAdmin, requireDeveloper, requireHuman, projectRole, user as currentUser } from './access.js';
import { audit } from './audit.js';
import { WorkItems } from './work-items.js';
import { GitIntegration } from './git.js';
import { bootstrapAdministrator } from './bootstrap.js';
import { createUserWithGeneratedPassword, resetUserWithGeneratedPassword } from './users.js';

export const db = new Db();
export const workItems = new WorkItems(db);
const git = new GitIntegration(db);
const app: Application=express();
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:'],connectSrc:["'self'"]}}}));
app.use(cookieParser());
app.use(express.json({limit:'2mb',verify:(req,_res,buf)=>{(req as Request).rawBody=Buffer.from(buf)}}));
app.use(authMiddleware(db));

const wrap=(fn:(req:Request,res:Response)=>any)=>(req:Request,res:Response,next:NextFunction)=>Promise.resolve().then(()=>fn(req,res)).catch(next);
const send=(res:Response,value:any,status=200)=>res.status(status).json(value);
const actor=(req:Request)=>req.actor;

app.get('/health',(_req,res)=>send(res,{status:'ok',database:'sqlite',time:db.now()}));
app.post('/api/auth/login',wrap(async(req,res)=>{const result=await login(db,req.body.username,req.body.password,{ip:req.ip,userAgent:req.get('user-agent')});const cookieOptions={secure:process.env.NODE_ENV==='production',sameSite:'strict' as const,maxAge:7*86400_000,path:'/'};res.cookie('pb_session',result.token,{...cookieOptions,httpOnly:true});res.cookie('pb_csrf',result.csrf,{...cookieOptions,httpOnly:false});send(res,{user:result.user,csrfToken:result.csrf})}));
app.post('/api/auth/logout',wrap((req,res)=>{requireHuman(actor(req));db.run('UPDATE sessions SET revoked_at=? WHERE id=?',db.now(),req.sessionId);res.clearCookie('pb_session',{path:'/'});res.clearCookie('pb_csrf',{path:'/'});send(res,{ok:true})}));
app.use('/api',csrfMiddleware(db));
app.use('/api',(req,_res,next)=>{try{if(req.actor.type==='human'&&req.actor.id){const forced=db.get<any>('SELECT must_change_password FROM users WHERE id=?',req.actor.id)?.must_change_password;if(forced&&!['/me','/me/change-password','/auth/logout'].includes(req.path))throw new DomainError(403,'PASSWORD_CHANGE_REQUIRED','Change the temporary password before continuing')}next()}catch(error){next(error)}});

app.get('/api/me',wrap((req,res)=>{const u=currentUser(db,actor(req));send(res,{id:u.id,username:u.username,displayName:u.display_name,systemRole:u.system_role,status:u.status,mustChangePassword:Boolean(u.must_change_password)})}));
app.patch('/api/me',wrap((req,res)=>{const u=currentUser(db,actor(req));db.run('UPDATE users SET display_name=?,updated_at=? WHERE id=?',String(req.body.displayName).slice(0,80),db.now(),u.id);audit(db,actor(req),'account.profile_updated','user',u.id,null,{});send(res,{ok:true})}));
app.post('/api/me/change-password',wrap(async(req,res)=>{const u=currentUser(db,actor(req));if(!validatePassword(req.body.newPassword))throw new DomainError(422,'WEAK_PASSWORD','Password must be 12-256 characters with letters and numbers');const {verifyPassword}=await import('./security.js');if(!await verifyPassword(u.password_hash,req.body.currentPassword))throw new DomainError(401,'INVALID_CREDENTIALS','Current password invalid');const nextHash=await hashPassword(req.body.newPassword);db.transaction(()=>{db.run('UPDATE users SET password_hash=?,must_change_password=0,updated_at=? WHERE id=?',nextHash,db.now(),u.id);db.run('UPDATE sessions SET revoked_at=? WHERE user_id=? AND id<>? AND revoked_at IS NULL',db.now(),u.id,req.sessionId);audit(db,actor(req),'account.password_changed','user',u.id,null,{})});send(res,{ok:true})}));
app.get('/api/me/sessions',wrap((req,res)=>{const u=currentUser(db,actor(req));send(res,db.all('SELECT id,user_agent,ip,expires_at,created_at,revoked_at FROM sessions WHERE user_id=? ORDER BY created_at DESC',u.id))}));
app.delete('/api/me/sessions/:id',wrap((req,res)=>{const u=currentUser(db,actor(req));const r=db.run('UPDATE sessions SET revoked_at=? WHERE id=? AND user_id=?',db.now(),String(req.params.id),u.id);if(!r.changes)throw new DomainError(404,'NOT_FOUND','Session not found');audit(db,actor(req),'auth.session_revoked','session',String(req.params.id),null,{});send(res,{ok:true})}));
app.get('/api/runner-downloads',wrap((req,res)=>{requireHuman(actor(req));const version=JSON.parse(readFileSync(resolve('package.json'),'utf8')).version;const dir=resolve('dist/downloads');const files=[{id:'package',name:`projectboard-runner-${version}.tgz`,platform:'Node.js 24+',description:'Installable Runner package'},{id:'windows',name:'projectboard-runner-tray.ps1',platform:'Windows',description:'System tray launcher'},{id:'linux',name:'projectboard-runner.service',platform:'Linux',description:'systemd service unit'}].map(file=>{const path=resolve(dir,file.name);return{...file,url:`/downloads/${file.name}`,available:existsSync(path),size:existsSync(path)?statSync(path).size:0}});send(res,{version,requirements:{node:'24+',codex:'Codex CLI signed in'},installCommand:`npm install --global ./projectboard-runner-${version}.tgz`,files})}));

app.get('/api/users',wrap((req,res)=>{requireAdmin(db,actor(req));send(res,db.all(`SELECT u.id,u.username,u.display_name displayName,u.system_role systemRole,u.status,u.last_active_at lastActiveAt,(SELECT COUNT(*) FROM project_memberships m WHERE m.user_id=u.id) membershipCount FROM users u ORDER BY u.display_name`))}));
app.post('/api/users',wrap(async(req,res)=>{requireAdmin(db,actor(req));send(res,await createUserWithGeneratedPassword(db,actor(req),{username:req.body.username,displayName:req.body.displayName,systemRole:req.body.systemRole}),201)}));
app.get('/api/users/:id',wrap((req,res)=>{requireAdmin(db,actor(req));const u=db.get<any>('SELECT id,username,display_name displayName,system_role systemRole,status,last_active_at lastActiveAt FROM users WHERE id=?',String(req.params.id));if(!u)throw new DomainError(404,'NOT_FOUND','User not found');u.memberships=db.all('SELECT m.project_id projectId,p.name,m.role FROM project_memberships m JOIN projects p ON p.id=m.project_id WHERE m.user_id=?',String(req.params.id));send(res,u)}));
app.patch('/api/users/:id',wrap((req,res)=>{requireAdmin(db,actor(req));db.run('UPDATE users SET display_name=COALESCE(?,display_name),system_role=COALESCE(?,system_role),updated_at=? WHERE id=?',req.body.displayName??null,req.body.systemRole??null,db.now(),String(req.params.id));audit(db,actor(req),'account.updated','user',String(req.params.id),null,req.body);send(res,{ok:true})}));
app.post('/api/users/:id/disable',wrap((req,res)=>{const admin=requireAdmin(db,actor(req));if(String(req.params.id)===admin.id)throw new DomainError(422,'SELF_DISABLE_FORBIDDEN','Cannot disable yourself');if(!req.body.reason?.trim())throw new DomainError(422,'REASON_REQUIRED','Reason required');const target=db.get<any>('SELECT * FROM users WHERE id=?',String(req.params.id));if(!target)throw new DomainError(404,'NOT_FOUND','User not found');if(target.system_role==='administrator'&&(db.get<any>("SELECT COUNT(*) n FROM users WHERE system_role='administrator' AND status='active'")?.n??0)<=1)throw new DomainError(422,'LAST_ADMIN','Cannot disable final administrator');db.transaction(()=>{db.run("UPDATE users SET status='disabled',disabled_reason=?,updated_at=? WHERE id=?",req.body.reason,db.now(),String(req.params.id));db.run('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL',db.now(),String(req.params.id));audit(db,actor(req),'account.disabled','user',String(req.params.id),null,{reason:req.body.reason})});send(res,{ok:true})}));
app.post('/api/users/:id/enable',wrap((req,res)=>{requireAdmin(db,actor(req));db.run("UPDATE users SET status='active',disabled_reason=NULL,updated_at=? WHERE id=?",db.now(),String(req.params.id));audit(db,actor(req),'account.enabled','user',String(req.params.id),null,{note:req.body.note});send(res,{ok:true})}));
app.post('/api/users/:id/reset-password',wrap(async(req,res)=>{requireAdmin(db,actor(req));send(res,await resetUserWithGeneratedPassword(db,actor(req),String(req.params.id)))}));

app.get('/api/projects',wrap((req,res)=>{requireHuman(actor(req));const u=currentUser(db,actor(req));const rows=u.system_role==='administrator'?db.all('SELECT * FROM projects ORDER BY name'):db.all('SELECT p.* FROM projects p JOIN project_memberships m ON m.project_id=p.id WHERE m.user_id=? ORDER BY p.name',u.id);send(res,rows.map(projectOut))}));
app.post('/api/projects',wrap((req,res)=>{const u=currentUser(db,actor(req));const id=db.id(),now=db.now(),key=String(req.body.key).toLowerCase();if(!/^[a-z][a-z0-9-]{1,19}$/.test(key))throw new DomainError(422,'INVALID_PROJECT_KEY','Invalid project key');db.transaction(()=>{db.run(`INSERT INTO projects(id,project_key,name,repository_url,allowed_target_branches_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`,id,key,req.body.name,req.body.repositoryUrl,JSON.stringify(['main']),now,now);db.run('INSERT INTO project_memberships VALUES(?,?,\'developer\',?)',id,u.id,now);audit(db,actor(req),'project.created','project',id,id,{key,repositoryUrl:req.body.repositoryUrl})});send(res,projectOut(db.get<any>('SELECT * FROM projects WHERE id=?',id)),201)}));
app.patch('/api/projects/:id',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));const p=db.get<any>('SELECT * FROM projects WHERE id=?',String(req.params.id));if(!p)throw new DomainError(404,'NOT_FOUND','Project not found');const cfg={...p,...req.body};db.run('UPDATE projects SET name=?,description_markdown=?,repository_url=?,remote_name=?,default_target_branch=?,allowed_target_branches_json=?,validation_commands_json=?,forbidden_paths_json=?,agent_rules_markdown=?,discussion_mode=?,execution_mode=?,acceptance_mode=?,config_version=config_version+1,updated_at=? WHERE id=?',cfg.name,cfg.descriptionMarkdown??p.description_markdown,cfg.repositoryUrl??p.repository_url,cfg.remoteName??p.remote_name,cfg.defaultTargetBranch??p.default_target_branch,JSON.stringify(cfg.allowedTargetBranches??JSON.parse(p.allowed_target_branches_json)),JSON.stringify(cfg.validationCommands??JSON.parse(p.validation_commands_json)),JSON.stringify(cfg.forbiddenPaths??JSON.parse(p.forbidden_paths_json)),cfg.agentRulesMarkdown??p.agent_rules_markdown,cfg.discussionMode??p.discussion_mode,cfg.executionMode??p.execution_mode,cfg.acceptanceMode??p.acceptance_mode,db.now(),String(req.params.id));db.run('UPDATE runner_repository_mappings SET paused_at=? WHERE project_id=?',db.now(),String(req.params.id));audit(db,actor(req),'project.settings_updated','project',String(req.params.id),String(req.params.id),{configVersion:p.config_version+1});send(res,projectOut(db.get<any>('SELECT * FROM projects WHERE id=?',String(req.params.id))))}));
app.get('/api/projects/:id/members',wrap((req,res)=>{projectRole(db,actor(req),String(req.params.id));send(res,db.all('SELECT u.id,u.username,u.display_name displayName,u.status,u.system_role systemRole,m.role,m.created_at createdAt FROM users u LEFT JOIN project_memberships m ON m.user_id=u.id AND m.project_id=? ORDER BY u.display_name',String(req.params.id)))}));
app.post('/api/projects/:id/members',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));db.run('INSERT INTO project_memberships VALUES(?,?,?,?)',String(req.params.id),req.body.userId,req.body.role,db.now());audit(db,actor(req),'membership.created','user',req.body.userId,String(req.params.id),{role:req.body.role});send(res,{ok:true},201)}));
app.patch('/api/projects/:id/members/:userId',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));db.run('UPDATE project_memberships SET role=? WHERE project_id=? AND user_id=?',req.body.role,String(req.params.id),String(req.params.userId));audit(db,actor(req),'membership.updated','user',String(req.params.userId),String(req.params.id),{role:req.body.role});send(res,{ok:true})}));
app.delete('/api/projects/:id/members/:userId',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));db.run('DELETE FROM project_memberships WHERE project_id=? AND user_id=?',String(req.params.id),String(req.params.userId));audit(db,actor(req),'membership.removed','user',String(req.params.userId),String(req.params.id),{});send(res,{ok:true})}));

app.get('/api/projects/:id/agents',wrap((req,res)=>{projectRole(db,actor(req),String(req.params.id));send(res,db.all(`SELECT a.id,a.name,a.purpose,a.status,CASE WHEN g.agent_id IS NULL THEN 0 ELSE 1 END enabled,(SELECT MAX(last_heartbeat_at) FROM runner_devices d WHERE d.agent_id=a.id) lastHeartbeatAt FROM agents a LEFT JOIN agent_project_grants g ON g.agent_id=a.id AND g.project_id=? ORDER BY a.name`,String(req.params.id)))}));
app.put('/api/projects/:id/agents/:agentId',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));db.run('INSERT OR IGNORE INTO agent_project_grants VALUES(?,?,?)',String(req.params.agentId),String(req.params.id),db.now());audit(db,actor(req),'agent.grant_enabled','agent',String(req.params.agentId),String(req.params.id),{});send(res,{ok:true})}));
app.delete('/api/projects/:id/agents/:agentId',wrap((req,res)=>{requireDeveloper(db,actor(req),String(req.params.id));db.transaction(()=>{db.run('DELETE FROM agent_project_grants WHERE agent_id=? AND project_id=?',String(req.params.agentId),String(req.params.id));db.run("UPDATE leases SET released_at=?,release_reason='grant_revoked' WHERE agent_id=? AND released_at IS NULL AND work_item_id IN(SELECT id FROM work_items WHERE project_id=?)",db.now(),String(req.params.agentId),String(req.params.id));audit(db,actor(req),'agent.grant_disabled','agent',String(req.params.agentId),String(req.params.id),{})});send(res,{ok:true})}));
app.post('/api/agents',wrap((req,res)=>{requireAdmin(db,actor(req));const id=db.id();db.run('INSERT INTO agents VALUES(?,?,?,\'active\',?,NULL)',id,req.body.name,req.body.purpose,db.now());audit(db,actor(req),'agent.created','agent',id,null,{name:req.body.name});send(res,{id,name:req.body.name},201)}));
app.post('/api/agents/:id/pairing-codes',wrap((req,res)=>{requireAdmin(db,actor(req));const raw=`PB-${randomToken(6).toUpperCase().slice(0,4)}-${randomToken(6).toUpperCase().slice(0,4)}`;db.transaction(()=>{db.run('UPDATE runner_pairing_codes SET invalidated_at=? WHERE agent_id=? AND consumed_at IS NULL AND invalidated_at IS NULL',db.now(),String(req.params.id));db.run('INSERT INTO runner_pairing_codes VALUES(?,?,?,?,?,?,?)',db.id(),String(req.params.id),hashOpaque(raw),new Date(Date.now()+600_000).toISOString(),null,null,db.now());audit(db,actor(req),'agent.pairing_code_created','agent',String(req.params.id),null,{expiresInSeconds:600})});send(res,{code:raw,expiresAt:new Date(Date.now()+600_000).toISOString(),command:`projectboard-runner connect ${raw}`},201)}));
app.post('/api/agent/pair',wrap((req,res)=>{const now=db.now();const code=db.get<any>('SELECT * FROM runner_pairing_codes WHERE code_hash=?',hashOpaque(req.body.code));if(!code||code.consumed_at||code.invalidated_at||code.expires_at<=now)throw new DomainError(409,'PAIRING_CODE_INVALID','Pairing code invalid or expired');const token=randomToken();const deviceId=db.id();db.transaction(()=>{const changed=db.run('UPDATE runner_pairing_codes SET consumed_at=? WHERE id=? AND consumed_at IS NULL AND invalidated_at IS NULL',now,code.id);if(!changed.changes)throw new DomainError(409,'PAIRING_CODE_CONSUMED','Pairing code already consumed');db.run('INSERT INTO runner_devices VALUES(?,?,?,?,?,?,?,?,?)',deviceId,code.agent_id,req.body.deviceName,req.body.os,req.body.version,req.body.publicKeyDigest,now,now,'idle');db.run('INSERT INTO agent_tokens VALUES(?,?,?,?,?)',db.id(),code.agent_id,hashOpaque(token),now,null);audit(db,{type:'agent',id:code.agent_id},'agent.paired','runner_device',deviceId,null,{deviceName:req.body.deviceName,os:req.body.os,version:req.body.version},'runner')});send(res,{agentToken:token,deviceId})}));

app.get('/api/activity',wrap((req,res)=>{requireHuman(actor(req));const u=currentUser(db,actor(req));const p=req.query.projectId as string|undefined;if(p)projectRole(db,actor(req),p);else if(u.system_role!=='administrator')throw new DomainError(403,'PROJECT_REQUIRED','Project scope required');let sql='SELECT * FROM activity_events WHERE 1=1';const a:any[]=[];if(p){sql+=' AND project_id=?';a.push(p)}if(req.query.actorType){sql+=' AND actor_type=?';a.push(req.query.actorType)}if(req.query.actorId){sql+=' AND actor_id=?';a.push(req.query.actorId)}if(req.query.eventType){sql+=' AND event_type LIKE ?';a.push(`${req.query.eventType}%`)}if(u.system_role!=='administrator')sql+=" AND event_type NOT LIKE 'auth.%' AND event_type NOT LIKE 'account.%'";if(req.query.query){sql+=' AND (event_type LIKE ? OR object_id LIKE ? OR payload_json LIKE ?)';a.push(...Array(3).fill(`%${req.query.query}%`))}if(req.query.cursor){sql+=' AND created_at<?';a.push(req.query.cursor)}sql+=' ORDER BY created_at DESC LIMIT 100';send(res,db.all(sql,...a).map((e:any)=>({...e,payload:JSON.parse(e.payload_json),payload_json:undefined})))}));
app.get('/api/activity/export',wrap((req,res)=>{requireAdmin(db,actor(req));const projectId=req.query.projectId?String(req.query.projectId):null;const rows=projectId?db.all<any>('SELECT * FROM activity_events WHERE project_id=? ORDER BY created_at',projectId):db.all<any>('SELECT * FROM activity_events ORDER BY created_at');audit(db,actor(req),'audit.exported','activity_export',db.id(),projectId,{count:rows.length});res.set({'content-type':'application/x-ndjson; charset=utf-8','content-disposition':`attachment; filename="projectboard-audit-${new Date().toISOString().slice(0,10)}.ndjson"`,'x-content-type-options':'nosniff'}).send(rows.map(r=>JSON.stringify({...r,payload:JSON.parse(r.payload_json),payload_json:undefined})).join('\n'))}));

app.get('/api/work-items',wrap((req,res)=>send(res,workItems.list(actor(req),String(req.query.projectId??''),req.query))));
app.get('/api/work-items/:id',wrap((req,res)=>send(res,workItems.get(actor(req),String(req.params.id)))));
app.post('/api/work-items',wrap((req,res)=>send(res,workItems.create(actor(req),req.body),201)));
app.patch('/api/work-items/:id',wrap((req,res)=>send(res,workItems.update(actor(req),String(req.params.id),req.body))));
for(const [path,method] of Object.entries({assign:'assign',unassign:'unassign',abandon:'abandon',block:'block',unblock:'unblock'}))app.post(`/api/work-items/:id/${path}`,wrap((req,res)=>send(res,(workItems as any)[method](actor(req),String(req.params.id),req.body))));
app.post('/api/work-items/:id/messages',wrap((req,res)=>send(res,workItems.message(actor(req),String(req.params.id),req.body),201)));
app.post('/api/work-items/:id/discussion-conclusions',wrap((req,res)=>send(res,workItems.freeze(actor(req),String(req.params.id),req.body),201)));
app.post('/api/work-items/:id/submit-execution',wrap((req,res)=>send(res,workItems.submitExecution(actor(req),String(req.params.id),req.body),201)));
app.post('/api/work-items/:id/acceptance-attempts',wrap((req,res)=>send(res,workItems.accept(actor(req),String(req.params.id),req.body),201)));
app.post('/api/work-items/:id/decomposition-proposals',wrap((req,res)=>send(res,workItems.decompose(actor(req),String(req.params.id),req.body),201)));
app.post('/api/work-items/:id/children',wrap((req,res)=>send(res,workItems.create(actor(req),{...req.body,parentId:String(req.params.id)}),201)));
app.post('/api/work-items/:id/attachments',express.raw({type:'*/*',limit:'25mb'}),wrap((req,res)=>{const item=workItems.get(actor(req),String(req.params.id)) as any;const body=Buffer.isBuffer(req.body)?req.body:Buffer.from(req.body.data??'','base64');const sha=createHash('sha256').update(body).digest('hex');const dir=resolve('data/attachments',item.project_id);mkdirSync(dir,{recursive:true});const key=`${String(req.params.id)}/${sha}`;const file=resolve(dir,sha);if(!existsSync(file))writeFileSync(file,body,{flag:'wx'});const id=db.id();db.run('INSERT OR IGNORE INTO attachments VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,String(req.params.id),null,String(req.headers['x-file-name']??'attachment'),String(req.headers['content-type']??'application/octet-stream'),body.length,sha,key,actor(req).type,actor(req).id,db.now());audit(db,actor(req),'attachment.uploaded','attachment',id,item.project_id,{name:req.headers['x-file-name'],mime:req.headers['content-type'],size:body.length,sha256:sha});send(res,{id,sha256:sha,size:body.length},201)}));
app.get('/api/attachments/:id',wrap((req,res)=>{const a=db.get<any>('SELECT a.*,w.project_id FROM attachments a JOIN work_items w ON w.id=a.work_item_id WHERE a.id=?',String(req.params.id));if(!a)throw new DomainError(404,'NOT_FOUND','Attachment not found');projectRole(db,actor(req),a.project_id);res.set({'Content-Type':a.mime,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(a.original_name)}`,'X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'",'Cache-Control':'private, no-store'}).send(readFileSync(resolve('data/attachments',a.project_id,a.sha256)))}));
app.post('/api/markdown/render',wrap((req,res)=>send(res,{html:renderMarkdown(req.body.markdown??'')})));

app.post('/api/agent/poll',wrap((req,res)=>{if(actor(req).type!=='agent'||!actor(req).id)throw new DomainError(401,'AGENT_REQUIRED','Agent required');const tasks=db.all(`SELECT w.* FROM work_items w JOIN agent_project_grants g ON g.project_id=w.project_id WHERE g.agent_id=? AND w.assignee_kind='agent' AND w.assignee_id=? AND w.assignment_state='reserved' AND w.blocked_at IS NULL AND w.stage NOT IN('completed','abandoned') AND NOT EXISTS(SELECT 1 FROM work_item_dependencies d JOIN work_items x ON x.id=d.depends_on_id WHERE d.work_item_id=w.id AND x.stage<>'completed') ORDER BY w.priority,w.created_at`,actor(req).id,actor(req).id);send(res,{assignments:tasks})}));
app.post('/api/agent/assignments/:id/accept',wrap((req,res)=>send(res,workItems.claim(actor(req),String(req.params.id),req.body.requestId,req.body.expectedVersion))));
app.post('/api/agent/runs/:id/heartbeat',wrap((req,res)=>send(res,workItems.heartbeat(actor(req),String(req.params.id),req.body.leaseId))));
app.post('/api/agent/runs/:id/events',wrap((req,res)=>send(res,workItems.message(actor(req),req.body.workItemId,req.body),201)));
app.post('/api/agent/runs/:id/commits',wrap((req,res)=>send(res,git.recordCommit(actor(req),req.body.workItemId,req.body),201)));
app.post('/api/agent/runs/:id/submit',wrap((req,res)=>send(res,workItems.submitExecution(actor(req),req.body.workItemId,req.body),201)));
app.post('/api/agent/runs/:id/release',wrap((req,res)=>send(res,workItems.release(actor(req),req.body.workItemId,req.body.leaseId,req.body.reason))));
app.post('/api/agent/runs/:id/git-credential',wrap(async(req,res)=>{if(actor(req).type!=='agent')throw new DomainError(401,'AGENT_REQUIRED','Agent required');const response=await fetch(`${process.env.PROJECTBOARD_BROKER_URL??'http://127.0.0.1:3334'}/internal/runner-credential`,{method:'POST',headers:{'content-type':'application/json','x-broker-secret':process.env.PROJECTBOARD_BROKER_SHARED_SECRET??''},body:JSON.stringify({runId:String(req.params.id),leaseId:req.body.leaseId,agentId:actor(req).id})});send(res,await response.json(),response.status)}));
app.delete('/api/agent/runs/:id/git-credential',wrap(async(req,res)=>{const response=await fetch(`${process.env.PROJECTBOARD_BROKER_URL??'http://127.0.0.1:3334'}/internal/revoke`,{method:'POST',headers:{'content-type':'application/json','x-broker-secret':process.env.PROJECTBOARD_BROKER_SHARED_SECRET??''},body:JSON.stringify({runId:String(req.params.id),agentId:actor(req).id})});send(res,await response.json(),response.status)}));

app.get('/api/git/installations',wrap((req,res)=>{requireAdmin(db,actor(req));send(res,db.all('SELECT * FROM git_installations'))}));
app.post('/api/git/installations/:provider/start',wrap((req,res)=>{requireAdmin(db,actor(req));const provider=String(req.params.provider);const state=randomToken(24);send(res,{provider,state,url:provider==='github'?`https://github.com/apps/${process.env.GITHUB_APP_SLUG??'projectboard'}/installations/new?state=${state}`:`${process.env.GITLAB_BASE_URL??'https://gitlab.com'}/oauth/authorize?client_id=${process.env.GITLAB_CLIENT_ID??''}&response_type=code&state=${state}`})}));
app.get('/api/git/installations/:provider/callback',wrap((req,res)=>{requireAdmin(db,actor(req));const id=db.id(),now=db.now();db.run('INSERT OR REPLACE INTO git_installations VALUES(?,?,?,?,?,?,?,?,?)',id,String(req.params.provider),String(req.query.installation_id??req.query.code),process.env.GITHUB_APP_ID??null,'[]','pending',JSON.stringify({contents:'write'}),now,now);audit(db,actor(req),'git.installation_registered','git_installation',id,null,{provider:String(req.params.provider)});send(res,{id,status:'registered'})}));
app.post('/api/projects/:id/repository-binding',wrap((req,res)=>{requireAdmin(db,actor(req));const id=db.id();db.run('INSERT OR REPLACE INTO repository_bindings VALUES(?,?,?,?,?,?,?,?)',id,String(req.params.id),req.body.installationId,req.body.provider,req.body.repositoryId,req.body.cloneUrl,req.body.defaultBranch,db.now());audit(db,actor(req),'git.repository_bound','repository_binding',id,String(req.params.id),{provider:req.body.provider,repositoryId:req.body.repositoryId});send(res,{id},201)}));
app.post('/api/git/webhooks/:provider',wrap(async(req,res)=>{const provider=String(req.params.provider);const raw=req.rawBody??Buffer.from(JSON.stringify(req.body));const accepted=git.webhook(provider,raw,req.headers);if((accepted as any).duplicate)return send(res,accepted);const reconciled=await git.reconcilePush(provider,req.body);send(res,{...accepted,reconciled})}));

const downloads=resolve('dist/downloads');if(existsSync(downloads))app.use('/downloads',(req,_res,next)=>{try{requireHuman(actor(req));next()}catch(error){next(error)}},express.static(downloads,{fallthrough:false,setHeaders:res=>res.setHeader('Content-Disposition',`attachment; filename="${encodeURIComponent(res.req.url.split('/').pop()??'runner-download')}"`)}));
const web=resolve('dist/web');if(existsSync(web)){app.use(express.static(web));app.get('/{*splat}',(_req,res)=>res.sendFile(resolve(web,'index.html')))}
app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{const status=err instanceof DomainError?err.status:err?.name==='ZodError'?422:err?.code?.startsWith('SQLITE_CONSTRAINT')?409:500;const code=err instanceof DomainError?err.code:err?.name==='ZodError'?'VALIDATION_ERROR':status===409?'CONFLICT':'INTERNAL_ERROR';if(status===500)console.error(err);res.status(status).json({error:{code,message:status===500?'Internal error':err.message,details:err instanceof DomainError?err.details:err?.issues}})});

function projectOut(p:any){return{id:p.id,key:p.project_key,name:p.name,descriptionMarkdown:p.description_markdown,archivedAt:p.archived_at,repositoryUrl:p.repository_url,remoteName:p.remote_name,defaultTargetBranch:p.default_target_branch,allowedTargetBranches:JSON.parse(p.allowed_target_branches_json),validationCommands:JSON.parse(p.validation_commands_json),forbiddenPaths:JSON.parse(p.forbidden_paths_json),agentRulesMarkdown:p.agent_rules_markdown,discussionMode:p.discussion_mode,executionMode:p.execution_mode,acceptanceMode:p.acceptance_mode,configVersion:p.config_version}}
async function bootstrap(){const credentials=await bootstrapAdministrator(db,{username:process.env.PROJECTBOARD_BOOTSTRAP_ADMIN,password:process.env.PROJECTBOARD_BOOTSTRAP_PASSWORD});if(credentials){console.log(`Bootstrap administrator created: ${credentials.username}`);if(credentials.generated)console.log(`Generated bootstrap password: ${credentials.password}`)}}
if(process.env.NODE_ENV!=='test'){await bootstrap();const port=Number(process.env.PORT??3333);app.listen(port,()=>console.log(`ProjectBoard listening on http://localhost:${port}`))}
export default app;
