import type { Db } from './db.js';
import type { Actor, WorkItem } from '../shared/types.js';
import { DomainError } from '../shared/types.js';
import { audit, timeline } from './audit.js';
import { idempotent } from './idempotency.js';
import { projectRole, requireDeveloper } from './access.js';
import { acceptanceSchema, conclusionSchema, executionSchema, workItemCreateSchema } from '../shared/validation.js';

const terminal = new Set(['completed','abandoned']);
export class WorkItems {
  constructor(private db: Db) {}
  get(actor: Actor, id: string) {
    const item = this.db.get<WorkItem>('SELECT * FROM work_items WHERE id=?', id); if (!item) throw new DomainError(404,'NOT_FOUND','Work item not found');
    projectRole(this.db, actor, item.project_id);
    return { ...item, conversation: this.db.all<any>('SELECT * FROM conversation_entries WHERE work_item_id=? ORDER BY created_at,id', id).map(e => ({ ...e, payload: JSON.parse(e.payload_json) })), conclusions: this.db.all('SELECT * FROM discussion_conclusions WHERE work_item_id=? ORDER BY version', id), executions: this.db.all('SELECT * FROM execution_attempts WHERE work_item_id=? ORDER BY number', id), acceptances: this.db.all('SELECT * FROM acceptance_attempts WHERE work_item_id=? ORDER BY number', id), dependencies: this.db.all('SELECT depends_on_id FROM work_item_dependencies WHERE work_item_id=?', id) };
  }
  list(actor: Actor, projectId: string, filters: any = {}) {
    projectRole(this.db, actor, projectId); let sql='SELECT * FROM work_items WHERE project_id=?'; const args:any[]=[projectId];
    if(filters.stage){sql+=' AND stage=?';args.push(filters.stage)} if(filters.blocked==='true')sql+=' AND blocked_at IS NOT NULL'; if(filters.query){sql+=' AND (title LIKE ? OR id LIKE ?)';args.push(`%${filters.query}%`,`%${filters.query}%`)}
    return this.db.all<WorkItem>(`${sql} ORDER BY CASE priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, updated_at DESC`,...args);
  }
  create(actor: Actor, input: unknown) {
    const data=workItemCreateSchema.parse(input); requireDeveloper(this.db,actor,data.projectId);
    return idempotent(this.db,'work-item:create',data.requestId,()=>this.db.transaction(()=>{
      const p=this.db.get<any>('SELECT * FROM projects WHERE id=?',data.projectId); if(!p)throw new DomainError(404,'NOT_FOUND','Project not found');
      if(data.parentId){const parent=this.db.get<any>('SELECT * FROM work_items WHERE id=? AND project_id=?',data.parentId,data.projectId);if(!parent)throw new DomainError(404,'NOT_FOUND','Parent not found');if(parent.parent_id)throw new DomainError(422,'MAX_DEPTH','Only two levels are allowed')}
      const n=(this.db.get<any>('SELECT COALESCE(MAX(number),0)+1 n FROM work_items WHERE project_id=?',data.projectId)?.n??1) as number;
      const id=`${p.project_key.toUpperCase()}-${n}`; const now=this.db.now(); const stage=data.assigneeId?'discussion':'todo';
      const branch=data.targetBranch??p.default_target_branch; this.validateBranch(p,branch);
      this.db.run(`INSERT INTO work_items(id,project_id,number,parent_id,title,description_markdown,acceptance_criteria_markdown,priority,stage,discussion_mode,execution_mode,acceptance_mode,target_branch,assignee_kind,assignee_id,assignment_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,data.projectId,n,data.parentId??null,data.title,data.descriptionMarkdown,data.acceptanceCriteriaMarkdown,data.priority,stage,data.discussionMode??p.discussion_mode,data.executionMode??p.execution_mode,data.acceptanceMode??p.acceptance_mode,branch,data.assigneeKind??null,data.assigneeId??null,data.assigneeId?'reserved':null,now,now);
      if(data.assigneeId)this.createAssignment(id,data.assigneeKind!,data.assigneeId,1);
      timeline(this.db,id,'stage_transition',stage,actor,{from:null,to:stage});audit(this.db,actor,'work_item.created','work_item',id,data.projectId,{stage,parentId:data.parentId});return this.get(actor,id);
    }));
  }
  update(actor:Actor,id:string,input:any){const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:update`,input.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,input.expectedVersion);if(terminal.has(current.stage))throw new DomainError(409,'TERMINAL','Terminal work items cannot change');const fields:any={};for(const [api,col] of Object.entries({title:'title',descriptionMarkdown:'description_markdown',acceptanceCriteriaMarkdown:'acceptance_criteria_markdown',priority:'priority'}))if(input[api]!==undefined)fields[col]=input[api];let stage=current.stage;if(input.targetBranch&&input.targetBranch!==current.target_branch){const p=this.db.get<any>('SELECT * FROM projects WHERE id=?',current.project_id)!;this.validateBranch(p,input.targetBranch);fields.target_branch=input.targetBranch;if(current.stage!=='todo'){stage='discussion';fields.stage=stage;this.releaseLease(id,'scope_changed');timeline(this.db,id,'stage_transition',stage,actor,{from:current.stage,to:stage,reason:'scope_changed'})}}this.apply(id,fields);audit(this.db,actor,'work_item.updated','work_item',id,current.project_id,{fields:Object.keys(fields)});return this.get(actor,id)}));}
  assign(actor:Actor,id:string,input:any){const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:assign`,input.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,input.expectedVersion);if(terminal.has(current.stage))throw new DomainError(409,'TERMINAL','Terminal work item');this.validateAssignee(current.project_id,input.assigneeKind,input.assigneeId);this.releaseLease(id,'assignee_changed');this.db.run("UPDATE assignments SET ended_at=?,ended_reason='assignee_changed' WHERE work_item_id=? AND ended_at IS NULL",this.db.now(),id);const generation=(current as any).lease_generation+1;this.createAssignment(id,input.assigneeKind,input.assigneeId,generation);const stage=current.stage==='todo'?'discussion':current.stage;this.apply(id,{assignee_kind:input.assigneeKind,assignee_id:input.assigneeId,assignment_state:'reserved',stage,lease_generation:generation});timeline(this.db,id,'assignment_changed',stage,actor,{from:{kind:current.assignee_kind,id:current.assignee_id},to:{kind:input.assigneeKind,id:input.assigneeId},reason:input.reason});if(stage!==current.stage)timeline(this.db,id,'stage_transition',stage,actor,{from:current.stage,to:stage});audit(this.db,actor,'assignment.changed','work_item',id,current.project_id,{assigneeKind:input.assigneeKind,assigneeId:input.assigneeId,generation});return this.get(actor,id)}));}
  unassign(actor:Actor,id:string,input:any){const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:unassign`,input.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,input.expectedVersion);this.releaseLease(id,'unassigned');this.db.run("UPDATE assignments SET ended_at=?,ended_reason='unassigned' WHERE work_item_id=? AND ended_at IS NULL",this.db.now(),id);this.apply(id,{assignee_kind:null,assignee_id:null,assignment_state:null,lease_generation:(current as any).lease_generation+1});timeline(this.db,id,'assignment_changed',current.stage,actor,{to:null,reason:input.reason});audit(this.db,actor,'assignment.removed','work_item',id,current.project_id,{});return this.get(actor,id)}));}
  block(actor:Actor,id:string,input:any){return this.simpleMutation(actor,id,input,'block',(item)=>{if(!input.reason?.trim())throw new DomainError(422,'REASON_REQUIRED','Block reason required');if(terminal.has(item.stage))throw new DomainError(409,'TERMINAL','Terminal item');this.releaseLease(id,'blocked');this.apply(id,{blocked_at:this.db.now(),blocked_reason:input.reason});timeline(this.db,id,'blocked',item.stage,actor,{reason:input.reason});return 'work_item.blocked'});}
  unblock(actor:Actor,id:string,input:any){return this.simpleMutation(actor,id,input,'unblock',(item)=>{if(!item.blocked_at)throw new DomainError(409,'NOT_BLOCKED','Work item is not blocked');this.apply(id,{blocked_at:null,blocked_reason:null});timeline(this.db,id,'unblocked',item.stage,actor,{});return 'work_item.unblocked'});}
  abandon(actor:Actor,id:string,input:any){return this.simpleMutation(actor,id,input,'abandon',(item)=>{if(!input.reason?.trim())throw new DomainError(422,'REASON_REQUIRED','Abandon reason required');if(terminal.has(item.stage))throw new DomainError(409,'TERMINAL','Terminal item');this.releaseLease(id,'abandoned');this.apply(id,{stage:'abandoned',abandoned_at:this.db.now(),abandoned_reason:input.reason,abandoned_from_stage:item.stage});timeline(this.db,id,'abandoned','abandoned',actor,{from:item.stage,reason:input.reason});return 'work_item.abandoned'});}
  message(actor:Actor,id:string,input:any){const item=this.row(id);projectRole(this.db,actor,item.project_id);if(!input.markdown?.trim()&&!input.attachmentIds?.length)throw new DomainError(422,'EMPTY_MESSAGE','Message is empty');return idempotent(this.db,`work-item:${id}:message`,input.requestId,()=>{const entry=timeline(this.db,id,'message',item.stage,actor,{markdown:input.markdown??'',attachmentIds:input.attachmentIds??[]},item.version);audit(this.db,actor,'message.posted','work_item',id,item.project_id,{entry});return {id:entry}});}
  freeze(actor:Actor,id:string,input:unknown){const data=conclusionSchema.parse(input);const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:conclusion`,data.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,data.expectedVersion);if(current.stage!=='discussion'||current.blocked_at)throw new DomainError(409,'INVALID_STAGE','Conclusion requires unblocked discussion');if(current.discussion_mode==='manual'&&actor.type==='agent')throw new DomainError(403,'HUMAN_CONFIRMATION_REQUIRED','Manual discussion requires a human');if(current.discussion_mode==='auto'&&actor.type!=='agent')throw new DomainError(403,'AGENT_CONCLUSION_REQUIRED','Automatic discussion requires an agent');this.requireCurrentExecutor(current,actor);const version=(this.db.get<any>('SELECT COALESCE(MAX(version),0)+1 n FROM discussion_conclusions WHERE work_item_id=?',id)?.n??1);this.db.run('INSERT INTO discussion_conclusions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',this.db.id(),id,version,data.goalMarkdown,data.scopeMarkdown,data.outOfScopeMarkdown,data.implementationPlanMarkdown,data.acceptanceCriteriaMarkdown,data.risksMarkdown,actor.type,actor.id,this.db.now(),version>1?version-1:null);this.apply(id,{stage:'execution'});timeline(this.db,id,'conclusion_frozen','discussion',actor,{...data,requestId:undefined,expectedVersion:undefined},version);timeline(this.db,id,'stage_transition','execution',actor,{from:'discussion',to:'execution'});this.startExecution(current,version);audit(this.db,actor,'conclusion.frozen','work_item',id,current.project_id,{version});return this.get(actor,id)}));}
  submitExecution(actor:Actor,id:string,input:unknown){const data=executionSchema.parse(input);const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:execution`,data.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,data.expectedVersion);if(current.stage!=='execution'||current.blocked_at)throw new DomainError(409,'INVALID_STAGE','Execution requires unblocked execution stage');this.requireCurrentExecutor(current,actor);if(!data.pushed&&!data.noCodeReason)throw new DomainError(422,'PUSH_REQUIRED','Task branch must be pushed');if(!data.worktreeClean||!data.forbiddenPathsClean)throw new DomainError(422,'EXECUTION_UNSAFE','Worktree or protected paths invalid');if(data.validations.some(v=>v.required&&v.exitCode!==0))throw new DomainError(422,'VALIDATION_FAILED','Required validation failed');const attempt=this.db.get<any>('SELECT * FROM execution_attempts WHERE work_item_id=? AND ended_at IS NULL ORDER BY number DESC LIMIT 1',id);if(!attempt)throw new DomainError(409,'NO_ATTEMPT','No active execution attempt');this.db.run('UPDATE execution_attempts SET summary_markdown=?,commits_json=?,changed_files_json=?,remaining_risks_markdown=?,pushed_at=?,ended_at=?,end_reason=? WHERE id=?',data.summaryMarkdown,JSON.stringify(data.commits),JSON.stringify(data.changedFiles),data.remainingRisksMarkdown,data.pushed?this.db.now():null,this.db.now(),'submitted',attempt.id);for(const v of data.validations){this.db.run('INSERT INTO validation_runs VALUES(?,?,?,?,?,?,?,?,?)',this.db.id(),attempt.id,v.name,null,v.required?1:0,v.exitCode,v.durationMs,v.logSummary,this.db.now());timeline(this.db,id,'validation','execution',actor,v)}this.releaseLease(id,'execution_submitted');this.apply(id,{stage:'acceptance',assignment_state:'reserved'});timeline(this.db,id,'stage_transition','acceptance',actor,{from:'execution',to:'acceptance'});this.startAcceptance(current,attempt.id);audit(this.db,actor,'execution.submitted','work_item',id,current.project_id,{attemptId:attempt.id,commits:data.commits});return this.get(actor,id)}));}
  accept(actor:Actor,id:string,input:unknown){const data=acceptanceSchema.parse(input);const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:acceptance`,data.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,data.expectedVersion);if(current.stage!=='acceptance'||current.blocked_at)throw new DomainError(409,'INVALID_STAGE','Acceptance requires unblocked acceptance stage');if(current.acceptance_mode==='human'&&actor.type!=='human')throw new DomainError(403,'HUMAN_ACCEPTANCE_REQUIRED','Human acceptance required');if(current.acceptance_mode!=='human'&&actor.type!=='agent')throw new DomainError(403,'AGENT_ACCEPTANCE_REQUIRED','Agent acceptance required');if(current.acceptance_mode!=='human'&&actor.id===current.assignee_id)throw new DomainError(403,'INDEPENDENCE_REQUIRED','Executor cannot accept own work');const attempt=this.db.get<any>('SELECT * FROM acceptance_attempts WHERE work_item_id=? AND completed_at IS NULL ORDER BY number DESC LIMIT 1',id);if(!attempt)throw new DomainError(409,'NO_ACCEPTANCE_ATTEMPT','No active acceptance attempt');const next:any={pass:'completed',changes_requested:'execution',scope_unclear:'discussion',abandon:'abandoned'}[data.outcome];this.db.run('UPDATE acceptance_attempts SET acceptor_type=?,acceptor_id=?,outcome=?,note_markdown=?,criteria_results_json=?,completed_at=? WHERE id=?',actor.type,actor.id,data.outcome,data.noteMarkdown,JSON.stringify(data.criteriaResults),this.db.now(),attempt.id);const fields:any={stage:next};if(next==='completed')fields.completed_at=this.db.now();if(next==='abandoned'){fields.abandoned_at=this.db.now();fields.abandoned_reason=data.noteMarkdown;fields.abandoned_from_stage='acceptance'}this.apply(id,fields);timeline(this.db,id,'acceptance_result','acceptance',actor,{attemptId:attempt.id,outcome:data.outcome,noteMarkdown:data.noteMarkdown,criteriaResults:data.criteriaResults});timeline(this.db,id,next==='abandoned'?'abandoned':'stage_transition',next,actor,{from:'acceptance',to:next});if(next==='execution'){const conclusion=this.db.get<any>('SELECT MAX(version) v FROM discussion_conclusions WHERE work_item_id=?',id)?.v;this.startExecution(current,conclusion)}audit(this.db,actor,'acceptance.completed','work_item',id,current.project_id,{outcome:data.outcome});this.checkParent(current.parent_id);return this.get(actor,id)}));}
  claim(actor:Actor,id:string,requestId:string,expectedVersion:number){if(actor.type!=='agent'||!actor.id)throw new DomainError(401,'AGENT_REQUIRED','Agent required');const item=this.row(id);projectRole(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:claim`,requestId,()=>this.db.transaction(()=>{const current=this.lock(id,expectedVersion);if(current.assignee_kind!=='agent'||current.assignee_id!==actor.id)throw new DomainError(409,'NOT_ASSIGNED','Work item is not assigned to this agent');if(current.blocked_at||terminal.has(current.stage))throw new DomainError(409,'NOT_CLAIMABLE','Work item cannot be claimed');if(this.db.get('SELECT 1 FROM leases WHERE agent_id=? AND released_at IS NULL AND expires_at>?',actor.id,this.db.now()))throw new DomainError(409,'AGENT_CAPACITY_EXCEEDED','Agent already has an active lease');const assignment=this.db.get<any>('SELECT * FROM assignments WHERE work_item_id=? AND ended_at IS NULL ORDER BY created_at DESC LIMIT 1',id);if(!assignment)throw new DomainError(409,'NO_ASSIGNMENT','Assignment missing');const lease={id:this.db.id(),expiresAt:new Date(Date.now()+30*60_000).toISOString()},runId=this.db.id();this.db.run('INSERT INTO leases(id,work_item_id,assignment_id,agent_id,generation,expires_at,created_at) VALUES(?,?,?,?,?,?,?)',lease.id,id,assignment.id,actor.id,assignment.generation,lease.expiresAt,this.db.now());this.db.run('INSERT INTO runner_runs VALUES(?,?,?,?,?,?,NULL,NULL)',runId,id,actor.id,lease.id,current.stage,this.db.now());this.db.run('INSERT INTO runner_status(agent_id,status,current_run_id,paused,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(agent_id) DO UPDATE SET status=excluded.status,current_run_id=excluded.current_run_id,updated_at=excluded.updated_at',actor.id,current.stage,runId,0,this.db.now());this.apply(id,{assignment_state:'active'});audit(this.db,actor,'lease.claimed','work_item',id,current.project_id,{leaseId:lease.id,runId,generation:assignment.generation},'runner');return {...lease,runId,workItem:this.get(actor,id)}}));}
  heartbeat(actor:Actor,runId:string,leaseId:string){if(actor.type!=='agent'||!actor.id)throw new DomainError(401,'AGENT_REQUIRED','Agent required');return this.db.transaction(()=>{const lease=this.db.get<any>('SELECT l.*,w.project_id FROM leases l JOIN work_items w ON w.id=l.work_item_id JOIN runner_runs r ON r.lease_id=l.id AND r.id=? AND r.agent_id=l.agent_id AND r.ended_at IS NULL WHERE l.id=? AND l.agent_id=?',runId,leaseId,actor.id);if(!lease||lease.released_at||lease.expires_at<=this.db.now())throw new DomainError(409,'LEASE_INVALID','Lease or run is no longer valid');const expiresAt=new Date(Date.now()+30*60_000).toISOString();this.db.run('UPDATE leases SET expires_at=? WHERE id=?',expiresAt,leaseId);this.db.run('UPDATE runner_status SET updated_at=? WHERE agent_id=?',this.db.now(),actor.id);audit(this.db,actor,'lease.heartbeat','lease',leaseId,lease.project_id,{runId,expiresAt},'runner');return {valid:true,expiresAt}});}
  release(actor:Actor,id:string,leaseId:string,reason='released'){const item=this.row(id);projectRole(this.db,actor,item.project_id);return this.db.transaction(()=>{const result=this.db.run('UPDATE leases SET released_at=?,release_reason=? WHERE id=? AND work_item_id=? AND released_at IS NULL',this.db.now(),reason,leaseId,id);if(!result.changes)throw new DomainError(409,'LEASE_INVALID','Lease already inactive');this.db.run('UPDATE runner_runs SET ended_at=?,end_reason=? WHERE lease_id=? AND ended_at IS NULL',this.db.now(),reason,leaseId);if(actor.type==='agent')this.db.run("UPDATE runner_status SET status='idle',current_run_id=NULL,updated_at=? WHERE agent_id=?",this.db.now(),actor.id);this.apply(id,{assignment_state:'reserved'});audit(this.db,actor,'lease.released','lease',leaseId,item.project_id,{reason},'runner');return{released:true}});}
  decompose(actor:Actor,id:string,input:any){const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);if(!Array.isArray(input.items)||input.items.length<2||input.items.length>20)throw new DomainError(422,'INVALID_DECOMPOSITION','Decomposition needs 2-20 items');const keys=new Set(input.items.map((x:any)=>x.key));if(keys.size!==input.items.length||input.items.some((x:any)=>!x.title||!x.acceptanceCriteriaMarkdown))throw new DomainError(422,'INVALID_DECOMPOSITION','Keys, titles and acceptance criteria required');for(const d of input.dependencies??[])if(!keys.has(d.from)||!keys.has(d.to)||d.from===d.to)throw new DomainError(422,'INVALID_DEPENDENCY','Invalid dependency');return idempotent(this.db,`work-item:${id}:decompose`,input.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,input.expectedVersion);if(current.parent_id)throw new DomainError(422,'MAX_DEPTH','Child items cannot be split');const created:any[]=[];for(const child of input.items){created.push(this.create(actor,{requestId:`${input.requestId}:${child.key}`,projectId:current.project_id,parentId:id,title:child.title,descriptionMarkdown:child.descriptionMarkdown??'',acceptanceCriteriaMarkdown:child.acceptanceCriteriaMarkdown,priority:child.priority??current.priority,targetBranch:current.target_branch,discussionMode:current.discussion_mode,executionMode:current.execution_mode,acceptanceMode:current.acceptance_mode}))}const byKey=new Map(input.items.map((x:any,i:number)=>[x.key,created[i].id]));for(const d of input.dependencies??[])this.db.run('INSERT INTO work_item_dependencies VALUES(?,?,?)',byKey.get(d.from),byKey.get(d.to),this.db.now());this.db.run('INSERT INTO decomposition_proposals VALUES(?,?,?,?,?,?,?,?,?)',this.db.id(),id,JSON.stringify(input.items),JSON.stringify(input.dependencies??[]),'materialized',actor.type,actor.id,this.db.now(),this.db.now());audit(this.db,actor,'decomposition.materialized','work_item',id,current.project_id,{children:created.map(x=>x.id)});return{children:created}}));}
  private simpleMutation(actor:Actor,id:string,input:any,op:string,fn:(item:any)=>string){const item=this.row(id);requireDeveloper(this.db,actor,item.project_id);return idempotent(this.db,`work-item:${id}:${op}`,input.requestId,()=>this.db.transaction(()=>{const current=this.lock(id,input.expectedVersion);const event=fn(current);audit(this.db,actor,event,'work_item',id,current.project_id,input);return this.get(actor,id)}));}
  private row(id:string){const item=this.db.get<any>('SELECT * FROM work_items WHERE id=?',id);if(!item)throw new DomainError(404,'NOT_FOUND','Work item not found');return item;}
  private lock(id:string,version:number){const item=this.row(id);if(item.version!==version)throw new DomainError(409,'VERSION_CONFLICT','Work item changed',{latestVersion:item.version,assignee:{kind:item.assignee_kind,id:item.assignee_id}});return item;}
  private apply(id:string,fields:any){fields.updated_at=this.db.now();fields.version=this.row(id).version+1;const keys=Object.keys(fields);this.db.run(`UPDATE work_items SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`,...keys.map(k=>fields[k]),id);}
  private validateAssignee(projectId:string,kind:string,id:string){if(kind==='human'){const u=this.db.get<any>(`SELECT u.status,u.system_role,m.role FROM users u LEFT JOIN project_memberships m ON m.user_id=u.id AND m.project_id=? WHERE u.id=?`,projectId,id);if(!u||u.status!=='active'||(u.system_role!=='administrator'&&u.role!=='developer'))throw new DomainError(422,'INVALID_ASSIGNEE','Human assignee must be an active developer or administrator')}else{if(!this.db.get('SELECT 1 FROM agents a JOIN agent_project_grants g ON g.agent_id=a.id WHERE a.id=? AND g.project_id=? AND a.status=\'active\'',id,projectId))throw new DomainError(422,'INVALID_ASSIGNEE','Agent is not enabled for project')}}
  private createAssignment(itemId:string,kind:string,id:string,generation:number){this.db.run('INSERT INTO assignments(id,work_item_id,assignee_kind,assignee_id,state,generation,created_at) VALUES(?,?,?,?,?,?,?)',this.db.id(),itemId,kind,id,'reserved',generation,this.db.now());}
  private releaseLease(itemId:string,reason:string){const runs=this.db.all<any>('SELECT r.id,r.agent_id FROM runner_runs r JOIN leases l ON l.id=r.lease_id WHERE l.work_item_id=? AND r.ended_at IS NULL',itemId);this.db.run('UPDATE leases SET released_at=?,release_reason=? WHERE work_item_id=? AND released_at IS NULL',this.db.now(),reason,itemId);this.db.run('UPDATE runner_runs SET ended_at=?,end_reason=? WHERE work_item_id=? AND ended_at IS NULL',this.db.now(),reason,itemId);for(const run of runs)queueMicrotask(()=>{void fetch(`${process.env.PROJECTBOARD_BROKER_URL??'http://127.0.0.1:3334'}/internal/revoke`,{method:'POST',headers:{'content-type':'application/json','x-broker-secret':process.env.PROJECTBOARD_BROKER_SHARED_SECRET??''},body:JSON.stringify({runId:run.id,agentId:run.agent_id})}).catch(()=>undefined)})}
  private startExecution(item:any,conclusionVersion:number){const n=this.db.get<any>('SELECT COALESCE(MAX(number),0)+1 n FROM execution_attempts WHERE work_item_id=?',item.id)?.n??1;const p=this.db.get<any>('SELECT project_key FROM projects WHERE id=?',item.project_id);this.db.run('INSERT INTO execution_attempts(id,work_item_id,number,assignee_kind,assignee_id,conclusion_version,target_branch,task_branch,lease_generation,started_at) VALUES(?,?,?,?,?,?,?,?,?,?)',this.db.id(),item.id,n,item.assignee_kind,item.assignee_id,conclusionVersion,item.target_branch,`projectboard/${p.project_key}/${item.number}`,item.lease_generation,this.db.now());}
  private startAcceptance(item:any,executionId:string){const n=this.db.get<any>('SELECT COALESCE(MAX(number),0)+1 n FROM acceptance_attempts WHERE work_item_id=?',item.id)?.n??1;const c=this.db.get<any>('SELECT MAX(version) v FROM discussion_conclusions WHERE work_item_id=?',item.id)?.v??0;this.db.run('INSERT INTO acceptance_attempts(id,work_item_id,number,execution_attempt_id,acceptor_type,conclusion_version,started_at) VALUES(?,?,?,?,?,?,?)',this.db.id(),item.id,n,executionId,item.acceptance_mode==='human'?'human':'agent',c,this.db.now());}
  private checkParent(parentId:string|null){if(!parentId)return;const open=this.db.get<any>("SELECT COUNT(*) n FROM work_items WHERE parent_id=? AND stage<>'completed'",parentId)?.n;if(open===0){const p=this.row(parentId);if(p.stage==='execution'){this.apply(parentId,{stage:'acceptance'});timeline(this.db,parentId,'stage_transition','acceptance',{type:'system',id:null},{from:'execution',to:'acceptance',reason:'children_completed'});this.startAcceptance(p,'')}}}
  private requireCurrentExecutor(item:any,actor:Actor){if(actor.type==='human'&&actor.id){const u=this.db.get<any>('SELECT system_role FROM users WHERE id=?',actor.id);if(u?.system_role==='administrator')return}if(item.assignee_kind!==actor.type||item.assignee_id!==actor.id)throw new DomainError(403,'EXECUTOR_REQUIRED','Only the current executor may perform this action');if(actor.type==='agent'&&!this.db.get('SELECT 1 FROM leases WHERE work_item_id=? AND agent_id=? AND released_at IS NULL AND expires_at>?',item.id,actor.id,this.db.now()))throw new DomainError(409,'LEASE_REQUIRED','An active lease is required')}
  private validateBranch(project:any,branch:string){const allowed=JSON.parse(project.allowed_target_branches_json) as string[];const ok=allowed.some(pattern=>pattern.endsWith('/*')?branch.startsWith(pattern.slice(0,-1)):branch===pattern);if(!ok)throw new DomainError(422,'TARGET_BRANCH_NOT_ALLOWED','Target branch is not allowed');}
}
