import { afterEach, describe, expect, it } from 'vitest';
import { WorkItems } from '../src/server/work-items.js';
import { fixture } from './helpers.js';

const cleanups:Array<()=>void>=[];afterEach(()=>{while(cleanups.length)cleanups.pop()!()});
describe('final work item state machine',()=>{
 it('requires the complete discussion → execution → acceptance → completed path',()=>{const f=fixture('flow');cleanups.push(f.cleanup);const service=new WorkItems(f.db);let x:any=service.create(f.actors.developer,{requestId:'request-create-1',projectId:f.ids.project,title:'Complete feature',descriptionMarkdown:'safe',acceptanceCriteriaMarkdown:'works',assigneeKind:'human',assigneeId:f.ids.developer});expect(x.stage).toBe('discussion');x=service.freeze(f.actors.developer,x.id,{requestId:'request-freeze-1',expectedVersion:x.version,goalMarkdown:'goal',scopeMarkdown:'scope',outOfScopeMarkdown:'none',implementationPlanMarkdown:'plan',acceptanceCriteriaMarkdown:'works',risksMarkdown:'risk'});expect(x.stage).toBe('execution');x=service.submitExecution(f.actors.developer,x.id,{requestId:'request-exec-001',expectedVersion:x.version,summaryMarkdown:'done',pushed:true,worktreeClean:true,forbiddenPathsClean:true,commits:['abc'],changedFiles:['src/a.ts'],validations:[{name:'test',required:true,exitCode:0,durationMs:1,logSummary:'ok'}],remainingRisksMarkdown:''});expect(x.stage).toBe('acceptance');x=service.accept(f.actors.developer,x.id,{requestId:'request-accept-1',expectedVersion:x.version,outcome:'pass',noteMarkdown:'all criteria pass',criteriaResults:[]});expect(x.stage).toBe('completed');expect(()=>service.block(f.actors.developer,x.id,{requestId:'request-block-01',expectedVersion:x.version,reason:'no'})).toThrow(/Terminal/);expect(x.conversation.map((e:any)=>e.kind)).toEqual(expect.arrayContaining(['conclusion_frozen','validation','acceptance_result']))});
 it('keeps blocked as an additive marker and supports rework outcomes',()=>{const f=fixture('blocked');cleanups.push(f.cleanup);const s=new WorkItems(f.db);let x:any=s.create(f.actors.developer,{requestId:'request-create-2',projectId:f.ids.project,title:'Task',descriptionMarkdown:'',acceptanceCriteriaMarkdown:'ok'});x=s.block(f.actors.developer,x.id,{requestId:'request-block-02',expectedVersion:x.version,reason:'dependency'});expect(x.stage).toBe('todo');expect(x.blocked_at).toBeTruthy();x=s.unblock(f.actors.developer,x.id,{requestId:'request-unblk-02',expectedVersion:x.version});expect(x.stage).toBe('todo');expect(x.blocked_at).toBeNull();x=s.abandon(f.actors.developer,x.id,{requestId:'request-aband-02',expectedVersion:x.version,reason:'obsolete'});expect(x.stage).toBe('abandoned');expect(x.abandoned_from_stage).toBe('todo')});
 it('rejects viewers and stale versions',()=>{const f=fixture('permission');cleanups.push(f.cleanup);const s=new WorkItems(f.db);expect(()=>s.create(f.actors.viewer,{requestId:'request-viewer-1',projectId:f.ids.project,title:'No',descriptionMarkdown:'',acceptanceCriteriaMarkdown:''})).toThrow(/Developer/);const x:any=s.create(f.actors.developer,{requestId:'request-stale-01',projectId:f.ids.project,title:'Task',descriptionMarkdown:'',acceptanceCriteriaMarkdown:''});expect(()=>s.assign(f.actors.developer,x.id,{requestId:'request-stale-02',expectedVersion:99,assigneeKind:'human',assigneeId:f.ids.developer,reason:'test'})).toThrow(/changed/)});
 it('requires an active executor lease and a different agent for independent acceptance',()=>{const f=fixture('independent');cleanups.push(f.cleanup);const s=new WorkItems(f.db);let x:any=s.create(f.actors.developer,{requestId:'request-agent-01',projectId:f.ids.project,title:'Agent work',descriptionMarkdown:'',acceptanceCriteriaMarkdown:'ok',assigneeKind:'agent',assigneeId:f.ids.agent,discussionMode:'auto',acceptanceMode:'independent_agent'});expect(()=>s.freeze(f.actors.agent,x.id,{requestId:'request-agent-02',expectedVersion:x.version,goalMarkdown:'g',scopeMarkdown:'s',outOfScopeMarkdown:'',implementationPlanMarkdown:'p',acceptanceCriteriaMarkdown:'ok',risksMarkdown:''})).toThrow(/lease/);s.claim(f.actors.agent,x.id,'request-agent-claim',x.version);x=s.get(f.actors.agent,x.id);x=s.freeze(f.actors.agent,x.id,{requestId:'request-agent-03',expectedVersion:x.version,goalMarkdown:'g',scopeMarkdown:'s',outOfScopeMarkdown:'',implementationPlanMarkdown:'p',acceptanceCriteriaMarkdown:'ok',risksMarkdown:''});x=s.submitExecution(f.actors.agent,x.id,{requestId:'request-agent-04',expectedVersion:x.version,summaryMarkdown:'done',pushed:true,worktreeClean:true,forbiddenPathsClean:true,commits:['a'],changedFiles:[],validations:[],remainingRisksMarkdown:''});expect(()=>s.accept(f.actors.agent,x.id,{requestId:'request-agent-05',expectedVersion:x.version,outcome:'pass',noteMarkdown:'self',criteriaResults:[]})).toThrow(/own work/);x=s.accept(f.actors.agent2,x.id,{requestId:'request-agent-06',expectedVersion:x.version,outcome:'pass',noteMarkdown:'independent pass',criteriaResults:[]});expect(x.stage).toBe('completed')});
});
