import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const base=process.env.PROJECTBOARD_URL??'http://localhost:3333';const token=process.env.PROJECTBOARD_AGENT_TOKEN;if(!token)throw new Error('PROJECTBOARD_AGENT_TOKEN is required');
async function api(path:string,method='GET',body?:unknown){const response=await fetch(`${base}${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(JSON.stringify(data));return data}
const server=new McpServer({name:'projectboard',version:'1.0.0'});
const output=(value:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(value,null,2)}]});
server.tool('list_projects','List projects visible to this identity',{},async()=>output(await api('/api/projects')));
server.tool('list_work_items','List project work items',{projectId:z.string(),stage:z.string().optional(),query:z.string().optional()},async x=>output(await api(`/api/work-items?${new URLSearchParams(Object.entries(x).filter(([,v])=>v!==undefined) as [string,string][]).toString()}`)));
server.tool('get_work_item','Get a work item and its continuous conversation',{id:z.string()},async x=>output(await api(`/api/work-items/${x.id}`)));
server.tool('create_work_item','Create a work item',{requestId:z.string(),projectId:z.string(),title:z.string(),descriptionMarkdown:z.string(),acceptanceCriteriaMarkdown:z.string(),priority:z.enum(['urgent','high','medium','low']).optional()},async x=>output(await api('/api/work-items','POST',x)));
server.tool('update_work_item','Update a work item',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),title:z.string().optional(),descriptionMarkdown:z.string().optional(),acceptanceCriteriaMarkdown:z.string().optional(),targetBranch:z.string().optional()},async({id,...body})=>output(await api(`/api/work-items/${id}`,'PATCH',body)));
server.tool('assign_work_item','Assign a human or enabled agent',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),assigneeKind:z.enum(['human','agent']),assigneeId:z.string(),reason:z.string()},async({id,...body})=>output(await api(`/api/work-items/${id}/assign`,'POST',body)));
server.tool('claim_next_task','Poll and claim the first reserved assignment',{requestId:z.string()},async({requestId})=>{const polled=await api('/api/agent/poll','POST',{});if(!polled.assignments[0])return output(null);const item=polled.assignments[0];return output(await api(`/api/agent/assignments/${item.id}/accept`,'POST',{requestId,expectedVersion:item.version}))});
server.tool('claim_task','Claim a reserved task',{id:z.string(),requestId:z.string(),expectedVersion:z.number()},async({id,...body})=>output(await api(`/api/agent/assignments/${id}/accept`,'POST',body)));
server.tool('heartbeat_task','Extend a lease',{runId:z.string(),leaseId:z.string()},async x=>output(await api(`/api/agent/runs/${x.runId}/heartbeat`,'POST',{leaseId:x.leaseId})));
server.tool('post_message','Post Markdown to the continuous conversation',{id:z.string(),requestId:z.string(),markdown:z.string(),expectedVersion:z.number().optional()},async({id,...body})=>output(await api(`/api/work-items/${id}/messages`,'POST',body)));
server.tool('upload_attachment','Upload a base64 attachment',{id:z.string(),requestId:z.string(),name:z.string(),mime:z.string(),dataBase64:z.string()},async x=>{const r=await fetch(`${base}/api/work-items/${x.id}/attachments`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':x.mime,'x-file-name':x.name,'x-request-id':x.requestId},body:Buffer.from(x.dataBase64,'base64')});return output(await r.json())});
server.tool('freeze_discussion_conclusion','Freeze a structured conclusion',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),goalMarkdown:z.string(),scopeMarkdown:z.string(),outOfScopeMarkdown:z.string(),implementationPlanMarkdown:z.string(),acceptanceCriteriaMarkdown:z.string(),risksMarkdown:z.string()},async({id,...body})=>output(await api(`/api/work-items/${id}/discussion-conclusions`,'POST',body)));
server.tool('submit_execution_result','Submit pushed and validated execution result',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),summaryMarkdown:z.string(),pushed:z.boolean(),worktreeClean:z.boolean(),forbiddenPathsClean:z.boolean(),commits:z.array(z.string()),changedFiles:z.array(z.string()),validations:z.array(z.object({name:z.string(),required:z.boolean(),exitCode:z.number(),durationMs:z.number(),logSummary:z.string()})),remainingRisksMarkdown:z.string()},async({id,...body})=>output(await api(`/api/work-items/${id}/submit-execution`,'POST',body)));
server.tool('submit_acceptance_result','Submit an immutable acceptance outcome',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),outcome:z.enum(['pass','changes_requested','scope_unclear','abandon']),noteMarkdown:z.string()},async({id,...body})=>output(await api(`/api/work-items/${id}/acceptance-attempts`,'POST',body)));
server.tool('submit_decomposition','Atomically create child work items and dependencies',{id:z.string(),requestId:z.string(),expectedVersion:z.number(),items:z.array(z.object({key:z.string(),title:z.string(),descriptionMarkdown:z.string(),acceptanceCriteriaMarkdown:z.string()})),dependencies:z.array(z.object({from:z.string(),to:z.string()}))},async({id,...body})=>output(await api(`/api/work-items/${id}/decomposition-proposals`,'POST',body)));
for(const [name,path,extra] of [['mark_task_blocked','block',{reason:z.string()}],['clear_task_blocked','unblock',{}],['abandon_work_item','abandon',{reason:z.string()}]] as const)server.tool(name,path,{id:z.string(),requestId:z.string(),expectedVersion:z.number(),...extra},async({id,...body}:any)=>output(await api(`/api/work-items/${id}/${path}`,'POST',body)));
server.tool('release_task','Release an active task lease',{id:z.string(),runId:z.string(),leaseId:z.string(),reason:z.string()},async x=>output(await api(`/api/agent/runs/${x.runId}/release`,'POST',{workItemId:x.id,leaseId:x.leaseId,reason:x.reason})));
await server.connect(new StdioServerTransport());
