// Tests only public HTTP/MCP interfaces of a newly deployed process; never reads SQLite.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const {once} = require('node:events');
const {randomBytes} = require('node:crypto');
const cases = [];
const test = (id, name, steps, expected, run) => cases.push({id, name, steps, expected, run});
let base, child, cookie='', csrf='', revision=0, token, tokenID, task, other, root, leaf, comment, attachment, backup, plan, cursor;
const password = 'Test-only-'+randomBytes(12).toString('hex');
const output = path.resolve(process.env.PB_TEST_OUTPUT || 'test-output/full');
const dataDir = path.join(output, 'data-'+Date.now());
const binary = path.resolve(process.argv[2] || 'dist/projectboard-test.exe');
let setupToken, rpcID=0;
async function request(url, {method='GET', body, headers={}, auth=true, status=200}={}) {
  if(headers.Host){const code=await new Promise((resolve,reject)=>{const q=require('node:http').get(base+url,{headers},r=>{r.resume();resolve(r.statusCode)});q.on('error',reject);q.setTimeout(15000,()=>q.destroy(Error('Host test timeout')))});assert.equal(code,status);return {};}
  const r = await fetch(base+url, {method, body:body===undefined?undefined:body instanceof FormData||Buffer.isBuffer(body)||typeof body==='string'?body:JSON.stringify(body), headers:{'X-Requested-With':'ProjectBoard',...(auth?{Cookie:cookie,'X-CSRF-Token':csrf}:{}),...headers}, signal:AbortSignal.timeout(15000)});
  const bytes = Buffer.from(await r.arrayBuffer());
  assert.equal(r.status,status,`${method} ${url}: ${bytes.toString().slice(0,350)}`);
  return {r, bytes, value:r.headers.get('content-type')?.includes('json')?JSON.parse(bytes):bytes};
}
async function login(pass=password) { const {r,value}=await request('/api/login',{method:'POST',body:{password:pass}});cookie=r.headers.get('set-cookie').split(';')[0];csrf=value.csrf; }
async function state(){const {value}=await request('/api/state');revision=value.revision;return value;}
async function save(s){const {value}=await request('/api/state',{method:'PUT',body:s});revision=value.revision;return value;}
async function rpc(method, params, expectedError=false) {
  const {value}=await request('/api/mcp',{method:'POST',body:{jsonrpc:'2.0',id:++rpcID,method,params},headers:{Authorization:'Bearer '+token,Accept:'application/json, text/event-stream','Content-Type':'application/json','MCP-Protocol-Version':'2025-03-26'},auth:false});
  assert.ok(!value.error,JSON.stringify(value.error));
  if(expectedError){assert.equal(value.result.isError,true);return value.result;}
  assert.ok(!value.result.isError,JSON.stringify(value.result));return value.result;
}
const called = new Set();
async function call(name,args={},error=false){
  await state();
  const result=await rpc('tools/call',{name,arguments:{project_id:'p1',expected_revision:revision,...args}},error);
  if(error)return result;
  called.add(name);
  const v=result.structuredContent||JSON.parse(result.content[0].text);if(v.revision!==undefined)revision=v.revision;return v;
}
async function upload(name, content, type='text/plain') {const form=new FormData();form.append('file',new Blob([content],{type}),name);return (await request('/api/attachments?project=p1',{method:'POST',body:form})).value;}
async function preview(a){return (await request('/api/attachments?project=p1&id='+a.id+'&preview=1')).value;}
async function rejectState(edit){const before=await state(),bad=structuredClone(before);edit(bad);await request('/api/state',{method:'PUT',body:bad,status:400});assert.deepEqual(await state(),before);}
const statuses=[{id:'created',name:'创建',kind:'todo'},{id:'doing',name:'进行中',kind:'active'},{id:'done',name:'已完成',kind:'done'},{id:'cancelled',name:'已取消',kind:'cancelled'}];
test('B001','本地进程健康与内嵌资源','随机端口启动独立程序，读取健康接口、HTML、JS、CSS','健康版本与 package.json 一致；资源均可读取',async()=>{assert.equal((await request('/api/health')).value.version,require('../package.json').version);for(const p of ['/','/app.js','/app.css'])assert.ok((await request(p)).bytes.length>100);});
test('B002','首次会话与登录保护','初始化前读取会话和工作空间','initialized=false，state 返回 401',async()=>{assert.equal((await request('/api/session')).value.initialized,false);await request('/api/state',{status:401});});
test('B003','错误初始化凭据','分别提交错误令牌和过短密码','请求均拒绝，仍可正确初始化',async()=>{await request('/api/setup',{method:'POST',body:{token:'bad',password},status:403});await request('/api/setup',{method:'POST',body:{token:setupToken,password:'short'},status:400});});
test('B004','管理员初始化与 Cookie','使用启动令牌设置密码，检查会话','设置成功；Cookie 为 HttpOnly、SameSite=Strict',async()=>{const {r,value}=await request('/api/setup',{method:'POST',body:{token:setupToken,password}});cookie=r.headers.get('set-cookie').split(';')[0];csrf=value.csrf;assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);assert.equal((await request('/api/session')).value.authenticated,true);});
test('B005','初始化仅一次','重复提交正确初始化令牌','409 拒绝重复初始化',async()=>{await request('/api/setup',{method:'POST',body:{token:setupToken,password},status:409});});
test('B006','请求来源和 CSRF','错误 Origin、Host 和 CSRF 请求','分别返回 403',async()=>{await request('/api/state',{headers:{Origin:'http://example.invalid'},status:403});await request('/api/state',{headers:{Host:'example.invalid'},status:403});await request('/api/state',{method:'PUT',body:{},headers:{'X-CSRF-Token':'bad'},status:403});});
test('B007','创建项目与设置持久化','保存两个不同项目、描述、目录、深色主题','重新读取字段完全保留',async()=>{let s=await state();s.theme='dark';s.projects=['p1','p2'].map((id,i)=>({id,name:'测试项目'+i,code:'QA'+i,description:'项目说明',directory:'D:\\测试',statuses,initialStatusId:'created',labels:[]}));s=await save(s);assert.equal((await state()).theme,'dark');assert.equal(s.projects.length,2);});
test('B008','项目简称与状态约束','重复简称、删除创建状态、增加待处理状态','每次拒绝且整体数据保持',async()=>{await rejectState(s=>s.projects[1].code='qa0');await rejectState(s=>s.projects[0].statuses.shift());await rejectState(s=>s.projects[0].statuses.push({id:'pending',name:'待处理',kind:'todo'}));});
test('B009','项目归档恢复与自定义状态','归档后恢复项目，添加自定义状态','归档标志与状态持久化',async()=>{let s=await state();s.projects[0].archived=true;s.projects[0].statuses.push({id:'review',name:'待验证',kind:'active'});await save(s);s=await state();assert.equal(s.projects[0].archived,true);s.projects[0].archived=false;await save(s);});
test('B010','修订冲突与原子保存','对同一修订提交两次不同内容','第二次 409，第一次内容保留',async()=>{let s=await state();const stale=structuredClone(s);s.projects[0].description='已保存';await save(s);stale.projects[0].description='旧覆盖';await request('/api/state',{method:'PUT',body:stale,status:409});assert.equal((await state()).projects[0].description,'已保存');});
test('B011','MCP 项目令牌','创建令牌，再读取令牌列表','令牌只在创建响应提供',async()=>{const {value}=await request('/api/tokens?project=p1',{method:'POST',body:{name:'测试客户端'},status:201});token=value.token;tokenID=value.id;assert.ok(token);const list=(await request('/api/tokens?project=p1')).value;assert.equal(list[0].token,undefined);});
test('B012','MCP 协议初始化与工具发现','发送 initialize 和 tools/list','协议返回成功，工具恰为 37 个',async()=>{assert.equal((await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'blackbox',version:'1'}})).serverInfo.name,'ProjectBoard');assert.equal((await rpc('tools/list',{})).tools.length,37);});
test('B013','MCP 读取修改项目及状态','get_project、update_project、list_project_statuses','字段更改可从 HTTP state 读取',async()=>{assert.equal((await call('get_project')).data.id,'p1');await call('update_project',{fields:{description:'MCP 修改'}});assert.equal((await state()).projects[0].description,'MCP 修改');assert.ok((await call('list_project_statuses')).items.some(s=>s.name==='创建'));});
test('B014','任务默认字段','create_task 仅提供标题，然后 get_task','创建状态、其他业务标量为空',async()=>{task=(await call('create_task',{title:'黑盒验收任务'})).data;other=(await call('create_task',{title:'关联任务'})).data;const t=(await call('get_task',{id:task.id})).data;assert.equal(t.status,'created');for(const k of ['priority','start','due','end','reminder','repeat','color'])assert.equal(t[k],'');assert.equal(t.progress,null);});
test('B015','所有任务标量设置与清空','逐个设置、读取、null 清空详细/优先级/日期/提醒/重复/颜色/进度','值一致，null 清空；0 进度保留',async()=>{for(const [k,v] of Object.entries({description:'详细正文',priority:'高',start:'2026-01-01',due:'2026-01-03',end:'2026-01-02',reminder:'2099-01-01T12:00',repeat:'weekly',color:'#123ABC',progress:0})){await call('update_task',{id:task.id,fields:{[k]:v}});assert.equal((await call('get_task',{id:task.id})).data[k],v);await call('update_task',{id:task.id,fields:{[k]:null}});assert.equal((await call('get_task',{id:task.id})).data[k],k==='progress'?null:'');}});
test('B016','任务边界与拒绝后原子性','提交进度 -1/101、无效日期/颜色/枚举、反向日期','全部拒绝且修订不改变',async()=>{for(const fields of [{progress:-1},{progress:101},{due:'2026-02-30'},{color:'red'},{priority:'最高'},{repeat:'yearly'},{start:'2026-02-02',end:'2026-02-01'}]){const before=await state();await call('update_task',{id:task.id,fields},true);assert.deepEqual(await state(),before);}});
test('B017','任务状态、排序与列表分页','move_task 设置自定义状态及排序，list_tasks 分页','状态/排序正确，两页对象不同',async()=>{await call('move_task',{id:task.id,status:'review',order:3.5});let t=(await call('get_task',{id:task.id})).data;assert.equal(t.status,'review');assert.equal(t.order,3.5);const a=await call('list_tasks',{limit:1});cursor=a.next_cursor;assert.ok(cursor);const b=await call('list_tasks',{limit:1,cursor});assert.notEqual(a.items[0].id,b.items[0].id);await call('update_task',{id:task.id,fields:{status:null}});assert.equal((await call('get_task',{id:task.id})).data.status,'created');});
test('B018','过期分页游标','写入后继续使用旧游标','拒绝旧游标',async()=>{await call('list_tasks',{cursor},true);});
test('B019','任务清单与三种任务关联','设置检查项及 related/blocks/subtask 关联，清空','结构和完成值保留，清空不删除关联任务',async()=>{for(const type of ['related','blocks','subtask']){const t=(await call('update_task',{id:task.id,fields:{checks:[{id:'check',text:'检查',done:true}],relations:[{id:other.id,type}]}})).data;assert.equal(t.relations[0].type,type);assert.equal(t.checks[0].done,true);}await call('update_task',{id:task.id,fields:{checks:[],relations:[]}});assert.equal((await call('get_task',{id:other.id})).data.id,other.id);});
test('B020','知识树与点分寻址','创建带内容根节点和子节点，按地址查找','父子均保留内容，地址等于 技术.开发',async()=>{root=(await call('create_knowledge_node',{name:'技术',content:'根内容'})).data;leaf=(await call('create_knowledge_node',{name:'开发',content:'子内容',parent:root.id})).data;assert.equal((await call('get_knowledge_node',{address:'技术.开发'})).data.id,leaf.id);assert.equal((await call('get_knowledge_subtree',{id:root.id})).items.length,2);assert.equal((await call('list_knowledge_nodes')).items.length,2);});
test('B021','知识改名移动与稳定引用','关联任务和知识，改名根、移动子节点，再解绑','地址变化，稳定 ID 引用保持，解绑保留对象',async()=>{await call('link_task_knowledge',{task_id:task.id,node_id:leaf.id});await call('link_knowledge_nodes',{node_id:root.id,other_id:leaf.id});await call('update_knowledge_node',{id:root.id,fields:{name:'工程',content:'新内容',pinned:true}});assert.equal((await call('get_knowledge_node',{address:'工程.开发'})).data.id,leaf.id);assert.ok((await call('get_task',{id:task.id})).data.knowledge.includes(leaf.id));await call('move_knowledge_node',{id:leaf.id,parent:null});assert.equal((await call('get_knowledge_node',{id:leaf.id})).data.address,'开发');await call('move_knowledge_node',{id:leaf.id,parent:root.id});await call('unlink_knowledge_nodes',{node_id:root.id,other_id:leaf.id});await call('unlink_task_knowledge',{task_id:task.id,node_id:leaf.id});assert.equal((await call('get_task',{id:task.id})).data.knowledge.length,0);});
test('B022','知识非法名称与循环','点号名称、同级重复、根移到子下、ID/地址不一致','各请求拒绝，树完整',async()=>{await call('create_knowledge_node',{name:'a.b'},true);await call('create_knowledge_node',{name:'工程'},true);await call('move_knowledge_node',{id:root.id,parent:leaf.id},true);await call('get_knowledge_node',{id:leaf.id,address:'工程'},true);assert.equal((await call('get_knowledge_subtree',{id:root.id})).items.length,2);});
test('B023','项目标签创建、批量添加和 AND/OR','创建重点/技术，标记任务和节点，查询 all/any','AND 只匹配同时含两标签的任务；OR 同时匹配节点',async()=>{await call('create_label',{name:'重点'});await call('create_label',{name:'技术'});await call('attach_labels',{target_type:'task',target_ids:[task.id],tags:['重点','技术']});await call('attach_labels',{target_type:'node',target_ids:[leaf.id],tags:['技术']});assert.equal((await call('search',{tags:['重点','技术'],match:'all'})).items.length,1);assert.equal((await call('search',{tags:['重点','技术'],match:'any'})).items.length,2);assert.equal((await call('list_labels')).items.length,2);});
test('B024','标签移除、改名与合并','移除任务技术标签，重点改名关键后合并到技术','去重、原有对象内容保留',async()=>{await call('detach_labels',{target_type:'task',target_ids:[task.id],tags:['技术']});await call('rename_label',{name:'重点',new_name:'关键'});await call('rename_label',{name:'关键',new_name:'技术'},true);await call('rename_label',{name:'关键',new_name:'技术',merge:true});assert.deepEqual((await call('get_task',{id:task.id})).data.tags,['技术']);});
test('B025','跨项目批量操作与搜索范围','p1 请求含 p2 任务，随后按中文关键词搜索','跨项目整批失败，搜索只含 p1',async()=>{let s=await state();const cross={...structuredClone(task),id:'cross',project:'p2',num:1,title:'跨项目验收任务'};s.tasks.push(cross);await save(s);const before=await state();await call('attach_labels',{target_type:'task',target_ids:[task.id,'cross'],tags:['越界']},true);assert.deepEqual(await state(),before);await call('get_task',{id:'cross'},true);assert.ok((await call('search',{query:'验收任务',type:'task'})).items.every(t=>t.value.project==='p1'));await rpc('tools/call',{name:'get_project',arguments:{project_id:'p2'}},true);});
test('B026','评论发表、回复、编辑与列表','创建正文及回复，编辑首条评论','正文更新，回复 ID 保留，列表两条',async()=>{comment=(await call('create_task_comment',{task_id:task.id,text:'初始留言'})).data;await call('create_task_comment',{task_id:task.id,text:'回复',reply_to:comment.id});await call('update_task_comment',{task_id:task.id,comment_id:comment.id,text:'更新留言'});const xs=(await call('list_task_comments',{task_id:task.id})).items;assert.equal(xs.length,2);assert.ok(xs.some(c=>c.text==='更新留言'));assert.ok(xs.some(c=>c.replyTo===comment.id));});
test('B027','评论删除与恢复','删除首条，再恢复','删除隐藏，恢复内容保持',async()=>{await call('delete_task_comment',{task_id:task.id,comment_id:comment.id});assert.equal((await call('list_task_comments',{task_id:task.id})).items.length,1);await call('restore_task_comment',{task_id:task.id,comment_id:comment.id});assert.equal((await call('list_task_comments',{task_id:task.id})).items.length,2);});
test('B028','空评论及无效回复','空正文无附件、自回复或不存在回复','各请求拒绝',async()=>{await call('create_task_comment',{task_id:task.id,text:''},true);await call('create_task_comment',{task_id:task.id,text:'回复',reply_to:'absent'},true);});
test('B029','MCP 附件上传、评论引用与下载','Base64 上传 Markdown，附加到评论并下载','下载字节和文件元数据一致',async()=>{attachment=(await call('upload_comment_attachment',{task_id:task.id,filename:'说明.md',mime:'text/markdown',data:Buffer.from('# 标题\n\n**内容**').toString('base64')})).data;await call('create_task_comment',{task_id:task.id,text:'文件留言',attachments:[attachment.id]});const got=(await call('get_comment_attachment',{task_id:task.id,attachment_id:attachment.id})).data;assert.equal(Buffer.from(got.data,'base64').toString(),'# 标题\n\n**内容**');});
test('B030','任务详细附件与下载','HTTP 上传普通文本，附加到任务详细并读取','详细正文与附件持久化，下载字节原样',async()=>{const a=await upload('普通文本.txt','<标签>中文正文');await call('update_task',{id:task.id,fields:{description:'固定详细',detailAttachments:[a]}});const got=await request('/api/attachments?project=p1&id='+a.id);assert.equal(got.bytes.toString(),'<标签>中文正文');assert.match(got.r.headers.get('content-disposition'),/attachment/);});
test('B031','图片预览','上传 PNG，读取预览和 inline 字节','kind=image，image/png，字节一致',async()=>{const b=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP9sAAAAASUVORK5CYII=','base64');const a=await upload('图片.png',b,'image/png');assert.equal((await preview(a)).kind,'image');const got=await request('/api/attachments?project=p1&id='+a.id+'&inline=1');assert.deepEqual(got.bytes,b);assert.match(got.r.headers.get('content-type'),/image\/png/);});
test('B032','文本编码与原样显示','上传 UTF8/BOM/UTF16LE/UTF16BE 文本','解码正文一致，尖括号保持文本',async()=>{for(const b of [Buffer.from('Hi<文>'),Buffer.concat([Buffer.from([239,187,191]),Buffer.from('Hi<文>')]),Buffer.concat([Buffer.from([255,254]),Buffer.from('Hi<文>','utf16le')]),Buffer.from([254,255,0,72,0,105,0,60,101,135,0,62])]){const a=await upload('编码.txt',b);assert.equal((await preview(a)).text,'Hi<文>');}});
test('B033','Markdown 排版和源码安全','上传标题/表格/代码/脚本/危险链接','渲染包含排版，源码保留，HTML 不含可执行脚本',async()=>{const source='# 标题\n\n|列|值|\n|---|---|\n|a|b|\n\n```js\nlet a=1\n```\n\n<script>alert(1)</script>\n\n[x](javascript:alert(1))';const a=await upload('预览.md',source,'text/markdown');const v=await preview(a);assert.equal(v.kind,'markdown');assert.equal(v.text,source);assert.match(v.html,/<table>/);assert.match(v.html,/<pre><code/);assert.ok(!v.html.includes('<script>'));assert.ok(!v.html.includes('href="javascript:'));});
test('B034','长文本截断与完整下载','上传超过 1MB 的中文文本','预览截断且 UTF8 完整；下载完整',async()=>{const b=Buffer.from('文'.repeat(350000));const a=await upload('长文本.txt',b);const v=await preview(a);assert.equal(v.truncated,true);assert.ok(!v.text.includes('\ufffd'));assert.deepEqual((await request('/api/attachments?project=p1&id='+a.id)).bytes,b);});
test('B035','附件范围与非法引用','从 p2 请求 p1 附件、伪造附件 ID、同区九附件','拒绝读取/保存',async()=>{await request('/api/attachments?project=p2&id='+attachment.id,statusOptions(404));await rejectState(s=>s.tasks[0].detailAttachments=[{id:'fake',name:'x',size:1,type:'text/plain'}]);await rejectState(s=>s.tasks[0].detailAttachments=Array.from({length:9},()=>attachment));});
function statusOptions(status){return {status};}
test('B036','二进制预览回退','上传 ZIP 类型字节，请求预览后下载','预览拒绝，下载保持字节',async()=>{const a=await upload('文件.zip',Buffer.from([80,75,0,1]),'application/zip');await request('/api/attachments?project=p1&id='+a.id+'&preview=1',{status:400});assert.deepEqual((await request('/api/attachments?project=p1&id='+a.id)).bytes,Buffer.from([80,75,0,1]));});
test('B037','提醒一次投递与已读','设置过去提醒，读取两次、标记已读','同一提醒只一条，已读消失',async()=>{await call('update_task',{id:task.id,fields:{reminder:'2020-01-01T12:00'}});let xs=(await request('/api/notifications')).value;const n=xs.find(n=>n.task===task.id);assert.ok(n);assert.equal((await request('/api/notifications')).value.filter(n=>n.task===task.id).length,1);await request('/api/notifications',{method:'POST',body:{id:n.id}});assert.ok(!(await request('/api/notifications')).value.some(x=>x.id===n.id));});
test('B038','每日/每周/月末重复任务','分别完成三种周期任务，重复提交完成','日期正确推进，只生成一个后继，重置状态',async()=>{for(const [repeat,date] of [['daily','2026-02-01'],['weekly','2026-02-07'],['monthly','2026-02-28']]){const t=(await call('create_task',{title:repeat,fields:{repeat,due:'2026-01-31'}})).data;await call('move_task',{id:t.id,status:'done'});await call('move_task',{id:t.id,status:'done'});const xs=(await state()).tasks.filter(x=>x.repeatedFrom===t.id);assert.equal(xs.length,1);assert.equal(xs[0].due,date);assert.equal(xs[0].status,'created');}});
test('B039','任务删除恢复及标签删除覆盖回收站','删除任务、删除标签、恢复任务','标签删除覆盖回收站，评论和附件保留',async()=>{await call('delete_task',{id:task.id});await call('delete_label',{name:'技术'});await call('restore_task',{id:task.id});const t=(await call('get_task',{id:task.id})).data;assert.deepEqual(t.tags,[]);assert.equal(t.notes.length,3);assert.equal(t.detailAttachments.length,1);});
test('B040','知识子树删除计划、提交和恢复','预览重复选择的根和子，提交后恢复根','去重数量 2，整树删除恢复，内容保持',async()=>{plan=(await call('preview_delete',{node_ids:[root.id,leaf.id]})).data;assert.equal(plan.count,2);await call('commit_delete',{plan_id:plan.plan_id});assert.equal((await call('list_knowledge_nodes')).items.length,0);await call('restore_knowledge_node',{id:root.id,parent:null});assert.equal((await call('get_knowledge_subtree',{id:root.id})).items.length,2);});
test('B041','删除计划修订过期','生成计划后修改项目，再提交旧计划','拒绝，目标保留',async()=>{const p=(await call('preview_delete',{task_ids:[other.id]})).data;await call('update_project',{fields:{description:'修订变化'}});await call('commit_delete',{plan_id:p.plan_id},true);assert.equal((await call('get_task',{id:other.id})).data.deleted,undefined);});
test('B042','完整 ZIP 备份与恢复','备份，修改正文，恢复 ZIP，再下载附件','内容恢复，附件字节保留，会话仍有效',async()=>{backup=(await request('/api/backup')).bytes;assert.equal(backup.subarray(0,2).toString(),'PK');const before=(await call('get_task',{id:task.id})).data;await call('update_task',{id:task.id,fields:{description:'将被恢复'}});await state();await request('/api/restore',{method:'POST',body:backup,headers:{'X-Revision':String(revision)}});const after=(await call('get_task',{id:task.id})).data;assert.equal(after.description,before.description);assert.equal((await request('/api/attachments?project=p1&id='+after.detailAttachments[0].id)).bytes.toString(),'<标签>中文正文');});
test('B043','损坏备份与旧修订恢复','提交损坏 ZIP 和旧修订 ZIP','损坏 400，旧修订 409，数据保持',async()=>{const before=await state();await request('/api/restore',{method:'POST',body:Buffer.from('PK broken'),headers:{'X-Revision':String(revision)},status:400});await request('/api/restore',{method:'POST',body:backup,headers:{'X-Revision':'0'},status:409});assert.deepEqual(await state(),before);});
test('B044','预览 JSON 导入','导入当前 schema2 JSON 的修改副本','内容更新，项目和附件保持',async()=>{const s=await state();s.projects[0].description='JSON 导入';for(const t of s.tasks)for(const a of [...t.detailAttachments,...t.notes.flatMap(c=>c.attachments||[])]){a.data=(await request('/api/attachments?project='+t.project+'&id='+a.id)).bytes.toString('base64');}await request('/api/restore',{method:'POST',body:JSON.stringify(s),headers:{'X-Revision':String(revision)}});assert.equal((await state()).projects[0].description,'JSON 导入');});
test('B045','MCP 37 工具均实际调用','对成功调用集合与 tools/list 比较','每一个已发现工具都存在成功调用',async()=>{const names=(await rpc('tools/list',{})).tools.map(t=>t.name);assert.deepEqual([...called].sort(),names.sort());});
test('B046','令牌撤销与请求头项目范围','错误 X-Project-ID，撤销令牌后调用','分别 403 和 401',async()=>{await request('/api/mcp',{method:'POST',body:{},headers:{Authorization:'Bearer '+token,'X-Project-ID':'p2'},status:403});await request('/api/tokens?project=p1&id='+tokenID,{method:'DELETE'});await request('/api/mcp',{method:'POST',body:{},headers:{Authorization:'Bearer '+token},status:401});});
test('B047','错误密码、改密及旧会话失效','错误密码登录，正确改密后使用旧 Cookie','错误登录 401，改密成功，旧会话 401',async()=>{await request('/api/login',{method:'POST',body:{password:'wrong-password'},status:401});const old=cookie;const {r,value}=await request('/api/password',{method:'POST',body:{old:password,password:password+'!'}});cookie=r.headers.get('set-cookie').split(';')[0];csrf=value.csrf;await request('/api/state',{headers:{Cookie:old},status:401});await login(password+'!');});
test('B048','退出登录与重新登录','退出后读 state，再登录','退出后 401，登录恢复数据',async()=>{await request('/api/logout',{method:'POST'});await request('/api/state',{status:401});await login(password+'!');assert.ok((await state()).tasks.length>0);});
test('B049','非法 JSON、接口方法和深链接','发送串接 JSON、POST 静态页，访问独立任务 URL','400、405，深链接可到应用',async()=>{await request('/api/state',{method:'PUT',body:'{}{}',status:400});await request('/',{method:'POST',status:405});assert.ok((await request('/projects/p1/tasks/'+task.id)).bytes.toString().includes('ProjectBoard'));await request('/missing.js',{status:404});});
test('B050','重启持久化与正常停止','保存状态，正常停止并从相同测试目录重启','重新登录后工作空间完整一致',async()=>{const before=await state();await stop();await start(false);await login(password+'!');assert.deepEqual(await state(),before);});
async function start(fresh=true){
  child=spawn(binary,['--data-dir',dataDir,'--listen','127.0.0.1:0','--no-browser'],{windowsHide:true,stdio:['ignore','pipe','pipe']});
  let text='';child.stderr.on('data',()=>{});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),15000);child.once('error',e=>{clearTimeout(timer);reject(e)});child.once('exit',code=>{clearTimeout(timer);reject(Error('startup exit '+code))});child.stdout.on('data',b=>{text+=b;const m=text.match(/http:\/\/127\.0\.0\.1:\d+/);if(m&&(!fresh||text.includes('#setup/'))){base=m[0];setupToken=text.match(/#setup\/([a-f0-9]+)/)?.[1];clearTimeout(timer);resolve();}})});
}
async function stop(){if(child&&child.exitCode===null){const p=child;const ended=once(p,'exit');await request('/api/shutdown',{method:'POST',status:202});const timer=setTimeout(()=>p.kill(),5000);const [code]=await ended;clearTimeout(timer);assert.equal(code,0);}}
if(process.argv.includes('--list')){console.log(JSON.stringify(cases.map(({run,...c})=>c),null,2));}
else (async()=>{fs.mkdirSync(dataDir,{recursive:true});const results=[];try{await start();for(const c of cases){const at=Date.now();try{await c.run();results.push({...c,run:undefined,status:'PASS',ms:Date.now()-at});console.log(c.id+' PASS '+c.name);}catch(e){results.push({...c,run:undefined,status:'FAIL',ms:Date.now()-at,error:e.stack});console.error(c.id+' FAIL '+e.message);process.exitCode=1;}}}catch(e){results.push({id:'HARNESS',status:'FAIL',error:e.stack});process.exitCode=1;}finally{try{await stop()}catch{child?.kill()}fs.writeFileSync(path.join(output,'blackbox.json'),JSON.stringify({at:new Date().toISOString(),binary,dataDir,base,results},null,2));}})();
