const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium,expect}=require('@playwright/test');
const cases=[];const test=(id,name,steps,expected,run)=>cases.push({id,name,steps,expected,run});
let browser,context,page,child,base,setupURL,taskURL;
const out=path.resolve(process.env.PB_TEST_OUTPUT||'test-output/full'),data=path.join(out,'browser-data-'+Date.now());
const password='Browser-test-'+require('node:crypto').randomBytes(10).toString('hex');
const action=(a)=>page.locator('[data-action="'+a+'"]:visible').first();
const modal=()=>page.locator('#dialog');
const waitEvent=(event)=>{const p=page.waitForEvent(event);p.catch(()=>{});return p;};
const close=()=>page.keyboard.press('Escape');
async function projectTasks(){if(page.url().includes('/tasks/'))await action('task-close').click();await page.getByRole('button',{name:'任务',exact:true}).click();}
async function openTask(){await page.goto(taskURL);await expect(page.locator('.task-title-button')).toContainText('浏览器验收任务');}
async function attach(actionName,files){const [chooser]=await Promise.all([page.waitForEvent('filechooser'),action(actionName).click()]);await chooser.setFiles(files);await expect(page.locator(actionName==='detail-attach'?'#task-detail-form .comment-pending':'#comment-form .comment-pending')).toContainText(files[0].name);}
async function currentState(){return await(await context.request.get(base+'/api/state')).json();}
test('U001','管理员首次设置页面','浏览器打开启动链接，设置并确认密码','进入项目页',async()=>{await page.goto(setupURL);await page.getByLabel('设置密码',{exact:true}).fill(password);await page.getByLabel('确认密码',{exact:true}).fill(password);await page.getByRole('button',{name:'创建工作空间',exact:true}).click();await expect(action('project-new')).toBeVisible();});
test('U002','创建项目','填写名称和简称，保存','项目导航出现对应名称',async()=>{await action('project-new').click();await modal().locator('[name=name]').fill('浏览器验收项目');await modal().locator('[name=code]').fill('UI');await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('#dialog')).toBeEmpty();await expect(page.locator('body')).toContainText('浏览器验收项目');});
test('U003','创建任务和独立页','新建任务仅填写标题，刷新独立 URL','标题保留，详细阅读态，只显示创建属性',async()=>{await projectTasks();await action('task-new').click();await modal().locator('[name=title]').fill('浏览器验收任务');await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.task-title-button')).toContainText('浏览器验收任务');taskURL=page.url();assert.match(taskURL,/#\/projects\/.+\/tasks\//);await page.reload();await expect(page.locator('.task-title-button')).toContainText('浏览器验收任务');await expect(page.locator('#task-detail-form')).toHaveCount(0);await expect(page.locator('.task-property')).toHaveCount(1);await expect(page.locator('.task-property')).toContainText('创建');});
test('U004','任务详细位置和唯一属性入口','检查详细和评论位置及属性加号','详细在评论上方，仅一个加号入口',async()=>{const a=await page.locator('.task-fixed-detail').boundingBox(),b=await page.locator('.task-conversation').boundingBox();assert.ok(a.y<b.y);await expect(page.locator('[data-action=task-fields]')).toHaveCount(1);});
test('U005','详细编辑取消与保存','输入后取消，再编辑保存','取消回阅读态；保存内容持久化',async()=>{await action('detail-edit').click();await page.getByLabel('任务详细内容').fill('取消文本');await action('detail-cancel').click();await expect(page.locator('#task-detail-form')).toHaveCount(0);await action('detail-edit').click();await page.getByLabel('任务详细内容').fill('固定任务详细 <文本>');await page.getByRole('button',{name:'保存任务详细',exact:true}).click();await expect(page.locator('.task-detail-reading')).toHaveText('固定任务详细 <文本>');});
test('U006','详细图片上传和缩放','编辑详细，选择图片保存，打开预览放大再适应窗口','图片加载、缩放控制有效',async()=>{await action('detail-edit').click();await attach('detail-attach',[{name:'验收图片.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP9sAAAAASUVORK5CYII=','base64')}]);await page.getByRole('button',{name:'保存任务详细',exact:true}).click();await page.locator('.task-fixed-detail [data-action=attachment-preview]').first().click();await expect(page.locator('.attachment-preview-image img')).toBeVisible();await action('image-zoom-in').click();await expect(page.locator('.file-preview-tools')).toContainText('125%');await action('image-fit').click();await expect(page.locator('.file-preview-tools')).toContainText('100%');await close();});
test('U007','发表评论、回复和删除恢复','发表正文，回复，再删除恢复第一条','回复引用可见，恢复后正文保留',async()=>{await page.getByLabel('评论内容').fill('浏览器留言');await page.getByRole('button',{name:'发表评论',exact:true}).click();await expect(page.locator('.comment-text')).toHaveText('浏览器留言');await action('comment-reply').click();await page.getByLabel('评论内容').fill('浏览器回复');await page.getByRole('button',{name:'发表评论',exact:true}).click();await expect(page.locator('.comment-item blockquote')).toContainText('浏览器留言');await action('comment-delete').click();await page.locator('#confirm-action').click();await expect(page.locator('.comment-deleted')).toBeVisible();await action('comment-restore').click();await expect(page.locator('.comment-text')).toHaveCount(2);});
test('U008','评论文件上传和 Markdown/源码/文本预览','评论上传 md 和 txt，逐个打开并切换源码','Markdown 渲染表格，源码显示标签，文本原样显示',async()=>{await attach('comment-attach',[{name:'说明.md',mimeType:'text/markdown',buffer:Buffer.from('# 浏览器预览\n\n|列|值|\n|---|---|\n|a|b|\n\n<script>window.bad=true</script>')},{name:'普通.txt',mimeType:'text/plain',buffer:Buffer.from('<标签>普通文本')}]);await page.getByRole('button',{name:'发表评论',exact:true}).click();await page.getByRole('button',{name:/说明.md/}).first().click();await expect(page.locator('.markdown-preview table')).toBeVisible();await action('file-source').click();await expect(page.locator('.text-preview')).toContainText('<script>');await close();await page.getByRole('button',{name:/普通.txt/}).first().click();await expect(page.locator('.text-preview')).toHaveText('<标签>普通文本');await close();});
test('U009','附件下载字节','点击普通文本下载入口','本地下载内容与上传一致',async()=>{const pending=waitEvent('download');await page.getByRole('button',{name:'下载 普通.txt',exact:true}).click();const d=await pending;assert.equal(fs.readFileSync(await d.path(),'utf8'),'<标签>普通文本');});
test('U010','浏览器多页面同步','第二页面打开同任务，第一页修改详细','第二页在轮询后显示新内容',async()=>{const second=await context.newPage();try{await second.goto(taskURL);await expect(second.locator('.task-detail-reading')).toBeVisible();await action('detail-edit').click();await page.getByLabel('任务详细内容').fill('跨页面同步内容');await page.getByRole('button',{name:'保存任务详细',exact:true}).click();await expect(second.locator('.task-detail-reading')).toHaveText('跨页面同步内容',{timeout:12000});}finally{await second.close()}});
test('U011','看板、列表、时间线和月份导航','返回任务面板，切换三种视图，前后月和本月','任务可从三种视图打开，未排期任务在待安排',async()=>{await projectTasks();await page.getByRole('button',{name:'看板',exact:true}).click();await expect(page.locator('.task-card')).toContainText('浏览器验收任务');await page.getByRole('button',{name:'列表',exact:true}).click();await expect(page.locator('table')).toContainText('浏览器验收任务');await page.getByRole('button',{name:'时间线',exact:true}).click();await expect(page.locator('.timeline-unscheduled')).toContainText('浏览器验收任务');await action('timeline-prev').click();await action('timeline-next').click();await action('timeline-today').click();await page.locator('.timeline-unscheduled [data-action=task-open]').click();await expect(page.locator('.task-title-button')).toBeVisible();});
test('U012','知识创建、地址定位和内容自动保存','创建根节点及子节点，输入内容后切换页面','点分地址定位子节点，重新打开内容保留',async()=>{await projectTasks();await page.getByRole('button',{name:'知识库',exact:true}).click();await action('node-new').click();await modal().locator('[name=name]').fill('技术');await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('#node-content')).toBeVisible();await page.locator('[data-action=node-new][data-parent]').first().click();await modal().locator('[name=name]').fill('开发');await modal().getByRole('button',{name:'保存',exact:true}).click();await page.locator('#node-content').fill('知识内容自动保存');await page.getByRole('button',{name:'任务',exact:true}).click();await page.getByRole('button',{name:'知识库',exact:true}).click();await page.locator('#node-address').fill('技术.开发');await action('address-go').click();await expect(page.locator('#node-content')).toHaveValue('知识内容自动保存');});
test('U013','知识节点历史与置顶','修改节点内容，保存后查看历史，切换置顶','历史含旧内容，置顶可取消',async()=>{await action('node-snapshot').click();await page.locator('#node-content').fill('知识第二版');await page.getByRole('button',{name:'任务',exact:true}).click();await page.getByRole('button',{name:'知识库',exact:true}).click();await action('node-history').click();await expect(modal()).toContainText('知识内容自动保存');await close();await action('node-pin').click();await expect(page.getByRole('button',{name:'取消置顶',exact:true})).toBeVisible();});
test('U014','任务和知识导出文件','分别下载 CSV、任务 JSON 和知识 JSON','格式与当前项目数据一致',async()=>{await action('nav-settings').click();for(const [a,kind] of [['export-tasks','csv'],['export-task-json','tasks']]){const waiting=waitEvent('download');await action(a).click();const text=fs.readFileSync(await(await waiting).path(),'utf8');if(kind==='csv')assert.ok(text.includes('浏览器验收任务'));else assert.equal(JSON.parse(text).tasks[0].title,'浏览器验收任务');}const waiting=waitEvent('download');await action('export-knowledge').click();assert.equal(JSON.parse(fs.readFileSync(await(await waiting).path(),'utf8')).nodes.length,2);});
test('U015','全局搜索并打开任务','搜索任务标题，点击结果','进入对应独立任务页面',async()=>{await action('search').click();await page.locator('#global-search').fill('浏览器验收任务');await page.locator('#search-results [data-type=task]').click();await expect(page.locator('.task-title-button')).toContainText('浏览器验收任务');});
test('U016','主题保存和移动布局','设置深色后刷新，缩至 390px，打开任务','深色保留，移动视口可操作任务',async()=>{await action('nav-settings').click();await page.locator('[data-action=theme][data-id=dark]').click();await page.reload();await expect(page.locator('body')).toHaveClass(/dark/);await page.setViewportSize({width:390,height:844});await openTask();await expect(page.getByLabel('评论内容')).toBeVisible();await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});});
test('U017','脚本异常检查','汇总本轮页面未捕获异常','无未捕获异常',async()=>{assert.deepEqual(errors,[]);});
test('U018','属性添加、清空与标签筛选','添加 0% 进度和标签，清空进度，按标签搜索','0% 可见；清空隐藏；标签结果含任务',async()=>{await openTask();for(const [key,value] of [['progress','0'],['tags','浏览器标签']]){await action('task-fields').click();await modal().locator('[data-field="'+key+'"]').click();await modal().locator('[name=value]').fill(value);await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(modal()).toBeEmpty();}await expect(page.locator('.task-property')).toContainText(['创建','0%','浏览器标签']);await page.locator('[data-action=task-field-clear][data-field=progress]').click();await expect(page.locator('[data-action=task-field-clear][data-field=progress]')).toHaveCount(0);await projectTasks();await page.getByRole('button',{name:'标签',exact:true}).click();await page.locator('[data-action=tag-toggle][data-tag="浏览器标签"]').click();await expect(page.locator('tbody')).toContainText('浏览器验收任务');});
test('U019','评论写入知识与手动历史恢复','将评论写入节点，保存历史，再修改和恢复','评论出现在节点，恢复历史正文',async()=>{await openTask();await action('note-to-node').click();const s=await currentState();const n=s.nodes.find(n=>n.name==='开发');await modal().locator('[name=node]').selectOption(n.id);await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(modal()).toContainText('编辑知识内容');await modal().getByRole('button',{name:'保存',exact:true}).click();await projectTasks();await page.getByRole('button',{name:'知识库',exact:true}).click();await page.locator('#node-address').fill('技术.开发');await action('address-go').click();await expect(page.locator('#node-content')).toContainText('浏览器留言');await action('node-snapshot').click();await page.locator('#node-content').fill('临时修改');await action('node-history').click();await action('history-restore').click();await page.locator('#confirm-action').click();await expect(page.locator('#node-content')).toContainText('浏览器留言');});
test('U020','我的工作筛选与提醒中心','打开我的工作，筛选项目，再打开提醒','任务保留在选定项目；提醒窗口可访问',async()=>{await action('nav-work').click();const s=await currentState();await page.locator('#work-project').selectOption(s.projects[0].id);await expect(page.locator('body')).toContainText('浏览器验收任务');await action('notifications').click();await expect(modal()).toContainText('开启桌面提醒');await close();});
test('U021','任务回收站恢复','删除任务，到回收站恢复并打开','详细、评论、标签保持',async()=>{await openTask();await action('task-delete').click();await page.locator('#confirm-action').click();await action('nav-trash').click();await action('task-restore').click();await openTask();await expect(page.locator('.comment-text')).toHaveCount(2);await expect(page.locator('.task-detail-reading')).toHaveText('跨页面同步内容');});
test('U022','项目归档与恢复','项目设置归档，再到设置恢复','归档后侧栏隐藏，恢复后出现',async()=>{await projectTasks();await action('project-edit').click();await action('project-archive').click();await page.locator('#confirm-action').click();await expect(page.locator('.project-nav')).toHaveCount(0);await action('nav-settings').click();await action('project-unarchive').click();await expect(page.locator('.project-nav')).toContainText('浏览器验收项目');});
test('U023','MCP 页面真实读取','打开 MCP 页运行默认 list_tasks','返回包含当前任务的 JSON',async()=>{await page.locator('.project-nav').click();await page.getByRole('button',{name:'MCP',exact:true}).click();await action('mcp-run').click();await expect(page.locator('#mcp-result')).toContainText('浏览器验收任务');});
test('U024','看板拖动、自定义状态与删除迁移','新增验证状态，拖入任务，删除状态迁移到进行中','拖动和迁移后状态持久化',async()=>{await page.setViewportSize({width:1920,height:1000});await projectTasks();await page.getByRole('button',{name:'看板',exact:true}).click();await action('status-manage').click();await action('status-new').click();await modal().locator('[name=name]').fill('验证中');await modal().locator('[name=kind]').selectOption('active');await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(modal()).toContainText('管理任务状态');await close();const s=await currentState(),id=s.projects[0].statuses.find(x=>x.name==='验证中').id;await page.locator('.task-card').dragTo(page.locator('[data-drop="'+id+'"]'));await expect(page.locator('[data-drop="'+id+'"] .task-card')).toHaveCount(1);await action('status-manage').click();await modal().locator('[data-action=status-delete][data-id="'+id+'"]').click();await modal().locator('[name=target]').selectOption('doing');await modal().getByRole('button',{name:'保存',exact:true}).click();await expect(modal()).toContainText('管理任务状态');await close();await expect(page.locator('[data-drop=doing] .task-card')).toHaveCount(1);await page.setViewportSize({width:1440,height:1000});});
test('U025','复制独立任务链接','点击复制任务链接，读取系统剪贴板','复制值与独立 URL 相同',async()=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await openTask();await action('task-copy-link').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),taskURL);});
test('U026','知识子树回收站恢复与永久删除','创建临时根节点，删除恢复，再删除并永久清理','恢复保留节点；永久清理后从存储消失',async()=>{await projectTasks();await page.getByRole('button',{name:'知识库',exact:true}).click();await action('node-new').click();await modal().locator('[name=name]').fill('临时清理节点');await modal().getByRole('button',{name:'保存',exact:true}).click();await action('node-delete').click();await page.locator('#confirm-action').click();await action('nav-trash').click();await action('node-restore').click();await modal().getByRole('button',{name:'保存',exact:true}).click();assert.ok((await currentState()).nodes.some(n=>n.name==='临时清理节点'&&!n.deleted));await page.locator('.project-nav').click();await page.getByRole('button',{name:'知识库',exact:true}).click();await page.locator('#node-address').fill('临时清理节点');await action('address-go').click();await action('node-delete').click();await page.locator('#confirm-action').click();await action('nav-trash').click();await action('node-purge').click();await page.locator('#confirm-action').click();assert.ok(!(await currentState()).nodes.some(n=>n.name==='临时清理节点'));});
test('U027','任务永久删除','创建临时任务，删除后从回收站永久清理','任务消失，原任务保留',async()=>{await page.locator('.project-nav').click();await projectTasks();await action('task-new').click();await modal().locator('[name=title]').fill('临时清理任务');await modal().getByRole('button',{name:'保存',exact:true}).click();await action('task-delete').click();await page.locator('#confirm-action').click();await action('nav-trash').click();await action('task-purge').click();await page.locator('#confirm-action').click();assert.ok(!(await currentState()).tasks.some(t=>t.title==='临时清理任务'));await openTask();});
const errors=[];
if(process.argv.includes('--list'))console.log(JSON.stringify(cases.map(({run,...c})=>c),null,2));
else(async()=>{fs.mkdirSync(data,{recursive:true});const results=[];try{
 child=spawn(path.resolve(process.argv[2]||'dist/projectboard-test.exe'),['--listen','127.0.0.1:0','--data-dir',data,'--no-browser'],{windowsHide:true});child.stderr.on('data',()=>{});
 let text='';await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('startup timeout')),15000);child.on('error',reject);child.stdout.on('data',b=>{text+=b;const m=text.match(/http:\/\/127\.0\.0\.1:\d+\/#setup\/[a-f0-9]+/);if(m){setupURL=m[0];base=setupURL.split('/#')[0];clearTimeout(timer);resolve()}})});
 browser=await chromium.launch({channel:process.env.PB_BROWSER_CHANNEL||'msedge',headless:true});context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true});page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));
 for(const c of cases){const at=Date.now();try{await c.run();results.push({...c,run:undefined,status:'PASS',ms:Date.now()-at});console.log(c.id+' PASS '+c.name);}catch(e){results.push({...c,run:undefined,status:'FAIL',error:e.stack,ms:Date.now()-at});console.error(c.id+' FAIL '+e.message);await page.screenshot({path:path.join(out,c.id+'-failure.png'),fullPage:true}).catch(()=>{});if(await modal().textContent())await close().catch(()=>{});else if(taskURL)await openTask().catch(()=>{});process.exitCode=1;}}
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await context.tracing.stop({path:path.join(out,'browser-trace.zip')});
}catch(e){results.push({id:'HARNESS',status:'FAIL',error:e.stack});console.error(e);process.exitCode=1;}finally{if(context){try{const s=await(await context.request.get(base+'/api/session')).json();await context.request.post(base+'/api/shutdown',{headers:{'X-CSRF-Token':s.csrf}})}catch{}}await browser?.close();if(child?.exitCode===null)child.kill();fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({at:new Date().toISOString(),base,data,results},null,2));}})();
