// Run against the dedicated acceptance workspace, never against a user's workspace.
const fs=require('node:fs'),assert=require('node:assert/strict');
const base=process.env.PB_TEST_URL||'http://127.0.0.1:7331';
const pass=process.env.PB_TEST_PASSWORD;if(!pass)throw Error('Set PB_TEST_PASSWORD for the acceptance workspace');
(async()=>{let cookie='',csrf='';async function api(path,options={}){const res=await fetch(base+'/api'+path,{...options,headers:{'X-Requested-With':'ProjectBoard','X-CSRF-Token':csrf,Cookie:cookie,...options.headers}});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];if(!res.ok)throw Error(await res.text());return res.headers.get('content-type')?.includes('application/json')?res.json():Buffer.from(await res.arrayBuffer())}
csrf=(await api('/login',{method:'POST',body:JSON.stringify({password:pass})})).csrf;
let state=await api('/state');const task=state.tasks.find(t=>t.title==='验收任务与附件');assert.ok(task,'Use the dedicated acceptance task');
const cases=[['预览说明.md','text/markdown','# Markdown 预览\n\n**重点内容**与普通文本。\n\n- [x] 图片预览\n- [x] 文本阅读\n\n| 功能 | 结果 |\n|---|---|\n| 表格 | 就绪 |\n\n```go\nfmt.Println("ProjectBoard")\n```\n\n<script>alert("xss")</script>'],['普通文本.txt','text/plain','普通文本阅读。\n<标签>保持原样显示。']];const attachments=[];
for(const [name,type,text] of cases){const form=new FormData();form.append('file',new Blob([text],{type}),name);const a=await api('/attachments?project='+task.project,{method:'POST',body:form});attachments.push(a);const preview=await api('/attachments?project='+task.project+'&id='+a.id+'&preview=1');assert.equal(preview.kind,name.endsWith('.md')?'markdown':'text');if(preview.html){assert.match(preview.html,/<table>/);assert.ok(!preview.html.includes('<script>'))};const bytes=await api('/attachments?project='+task.project+'&id='+a.id);assert.equal(bytes.toString(),text)}
task.notes.push({id:crypto.randomUUID(),text:'附件预览验收',at:new Date().toISOString(),attachments});state=await api('/state',{method:'PUT',body:JSON.stringify(state)});const backup=await api('/backup');fs.mkdirSync('test-output',{recursive:true});fs.writeFileSync('test-output/acceptance-backup.zip',backup);fs.writeFileSync('test-output/live-check.json',JSON.stringify({url:base,revision:state.revision,task:task.id,attachmentPreview:['image','markdown','text'],byteVerification:'passed',backupBytes:backup.length},null,2));console.log('Live preview and download checks passed; backup bytes:',backup.length);
})().catch(e=>{console.error(e);process.exitCode=1});
