const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const elements=new Map(),data=new Map(),session=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',classList:{toggle(){},remove(){},add(){}},focus(){},replaceChildren(n){this.textContent=n.textContent},querySelectorAll(){return []},setAttribute(){}});return elements.get(id)};
const storage=map=>({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});
let transport='ok',release;
const context=vm.createContext({console,crypto:webcrypto,TextEncoder,Blob,URL,Response,Date,Set,Map,structuredClone,localStorage:storage(data),sessionStorage:storage(session),setTimeout:()=>0,setInterval:()=>0,clearTimeout(){},location:{hash:'',origin:'http://localhost',href:'http://localhost'},history:{pushState(){},replaceState(){}},FormData:class{constructor(target){this.values=target.values}get(k){return this.values[k]??''}},navigator:{clipboard:{writeText:async()=>{}}},document:{activeElement:{tagName:'BODY'},hidden:false,getElementById:el,body:{classList:{toggle(){}}},querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},createTextNode:text=>({textContent:text})},window:{addEventListener(){}},fetch:async(url,options)=>{if(transport==='hold')await new Promise(resolve=>release=resolve);if(transport==='conflict')return new Response(JSON.stringify({error:'REVISION_CONFLICT'}),{status:409,headers:{'Content-Type':'application/json'}});const next=JSON.parse(options.body);next.revision++;return new Response(JSON.stringify(next),{headers:{'Content-Type':'application/json'}})}});
let script=fs.readFileSync(__dirname+'/src/app.js','utf8');script=script.slice(0,script.lastIndexOf('bootstrap().catch'));vm.runInContext(script,context);const run=s=>vm.runInContext(s,context);
run(`db={schema:2,revision:0,theme:'light',projects:[{id:'p',name:'项目',code:'PB',statuses:baseStatuses(),initialStatusId:'created'}],nodes:[],tasks:[{id:'t',project:'p',num:1,title:'任务',description:'详细正文',status:'created',priority:'',due:'',start:'',end:'',tags:[],knowledge:[],checks:[],notes:[],relations:[],detailAttachments:[]}]};ui.project='p';ui.task='t';ui.page='task';logged=true;render()`);
const cases=[];async function test(name,fn){try{await fn();cases.push({name,status:'PASS'})}catch(e){cases.push({name,status:'FAIL',error:e.message});console.error(name,e);process.exitCode=1}}
(async()=>{
await test('任务详细默认阅读，位于评论上方',()=>{const html=el('task-page').innerHTML;assert.ok(html.indexOf('任务详细')<html.indexOf('任务评论'));assert.ok(!html.includes('id="task-detail-form"'));assert.equal((html.match(/data-action="task-fields"/g)||[]).length,1)});
await test('阅读状态的详细正文允许后台同步',()=>{assert.equal(run('hasUserDraft()'),false);run("detailDraft(db.tasks[0]).editing=true");assert.equal(run('hasUserDraft()'),true);run("detailDraft(db.tasks[0]).editing=false")});
await test('评论等待服务端确认后才报告发表',async()=>{transport='hold';run("commentDraft('t').text='等待确认的评论'");const pending=run('postComment()');await new Promise(setImmediate);assert.equal(run('saving'),true);assert.ok(!el('toast').textContent.includes('评论已发表'));release();await pending;assert.equal(el('toast').textContent,'评论已发表');assert.equal(run('db.revision'),1);assert.equal(run("commentDraft('t').text"),'')});
await test('冲突回滚并保留评论草稿',async()=>{transport='conflict';run("commentDraft('t').text='保留我的草稿'");await run('postComment()');assert.equal(run('db.tasks[0].notes.length'),1);assert.equal(run("commentDraft('t').text"),'保留我的草稿');assert.ok(el('dialog').innerHTML.includes('导出当前副本'));run("blocked=false;commentDraft('t').text='';closeModal()");transport='ok'});
await test('附件提供预览与独立下载入口',()=>{const html=run("attachmentHTML({id:'a',name:'图片.png',type:'image/png',size:1,sha256:'hash'},'c')");assert.ok(html.includes('data-action="attachment-preview"'));assert.ok(html.includes('data-action="comment-download"'));assert.ok(html.includes('inline=1'))});
await test('项目独立标签与实体标签共同显示',()=>{run("db.projects[0].labels=['独立'];db.tasks[0].tags=['任务标签']");assert.deepEqual(Array.from(run('allTags()')).sort(),['任务标签','独立'].sort())});
await test('局域网 HTTP 使用安全随机 ID',()=>{run("globalThis.originalCrypto=crypto;globalThis.crypto={getRandomValues:a=>originalCrypto.getRandomValues(a)}");assert.match(run('uid()'),/^[a-f0-9]{32}$/);run('globalThis.crypto=originalCrypto')});
fs.mkdirSync('test-output',{recursive:true});fs.writeFileSync('test-output/web-tests.json',JSON.stringify(cases,null,2));console.log(`${cases.filter(c=>c.status==='PASS').length}/${cases.length} production web checks passed`);
})();
